### PR TITLE
Add documentation for $Shape<T>

### PR DESCRIPTION
**Pull request by sanohin**
Part of #2464

### CODE REVIEW

**Comment by sanohin** [comment]
Is that ok to land?

**Comment by vicapow** [comment]
Is there hesitation in landing this?

**Comment by mrkev** [comment]
Oh, hello

**Comment by mrkev** [comment]
Ok, got it reviewed, and someone from the core team offered some insight. The main points:

- It was implemented for it's utility when typing React in a somewhat ad-hoc way. There might be edge-cases that are not considered, and the intended semantics have not been fully thought out.
- We can't stop people from digging through the code and discovering this stuff. It's used on React libdefs so it's also not going away soon, but there's hesitation on documenting it and making it "official"-- especially with some other work the team is doing around objects at the moment.
- "I don't think we should publicly document it yet."

It'll probably reach a point at which the team will be comfortable documenting it though-- especially considering it's shown it's utility in a number of scenarios.

**Comment by sibelius** [comment]
@mrkev I think flow should be more open on what is the roadmap or what the core team is working on

basically most of what React team does or relay meeting notes 

this could get more people from community engaged with flow

**Pull request closed without merging**
