### PR TITLE
Add docs for $ElementType

### PR DESCRIPTION
**Pull request by apsavin**
Part of #2464

### CODE REVIEW

**Comment by apsavin** [comment]
cc @gabelevi

**Comment by jcready** [comment]
Can anyone explain why one would ever use `$PropertyType` over `$ElementType` since string literals are also valid flow types?

**Comment by MOZGIII** [comment]
I can find a reason to do so in a "perfect" world. So in the "real" world, the only reason may be if `$ElementType` is buggy or not implemented.

**Comment by mrkev** [comment]
If @MOZGIII is right then it makes little sense to document $ElementType, because you'd be informing encouraging a buggy feature. If not, it makes little sense to document because it's essentially like $PropertyType, except more error prone since you might use types that don't resolve to strings.

Either way, I don't think documenting this makes sense.

**Comment by mrkev** [comment]
rip

**Pull request closed without merging**
