### PR TITLE
[FIX] [Typing function] Make function params required by default

### PR DESCRIPTION
**Pull request by moroine**
**Fix:**
- #8190

**Changes:**

Function params are assumed required by default ~> will cause new errors, which can be fixed using optional `?`

I think this change will improve library definitions using function overloading with generic params.

Currently, the only way to achieve this is using rest params:

```typescript
function fn(...args: [string]) {}
```

but this is too restrictive, as it can't be passed to as a callback

```typescript
function fn1(...r: [string]): void {}
function fn2(a: string): void {}

function callFn(f: (string, number) => void) {
  f('hello', 2); 
}

// Expected error
callFn(fn1);

// No error
callFn(fn2);
```

### CODE REVIEW

**Comment by moroine** [comment]
@jbrown215 what's your opinion about making function min-arity strict?

**Comment by jbrown215** [comment]
Discussed in discord, mirroring here:

I think the crux of the issue here is that you only want to be able to omit a function argument if it is optional:
```
function f(a?: number) {}
f(); // Ok
```

But not if it accepts `undefined`-- in that case you want to explicitly force people to pass the undefined:

```
function g(a: ?number) {}
g(); // Error
g(undefined); // Ok
```

Without thinking too hard about it, this seems like a desirable change and how optional function arguments should work in the first place. I also think they should _not_ accept undefined, but that can be addressed later.

Will need to discuss with some other people on our side and come to consensus before taking a look at the code changes.

**Comment by moroine** [comment]
@jbrown215 any update?

**Comment by jbrown215** [comment]
Will need to import and see how hard this will be to roll out before I can give a solid answer.

**Comment by moroine** [comment]
@jbrown215 I've added a codemod for explicit optional parameters. I should handle all typed functions. Only missing resolving imports & inference because it's not using FlowJS.

**Comment by jbrown215** [comment]
Cross posting here for visibility:
After importing and rebasing, this PR crashes on our repos internally. This could be for many reasons, and I cannot prioritize this over my other work.

**Pull request closed without merging**
