### PR TITLE
Build hack/utils/handle_stubs.o

### PR DESCRIPTION
**Pull request by mroch**
See related hack diff: https://github.com/facebook/hhvm/commit/7115d5c37d4cf7fedc747f193fddc33927505fcb

### CODE REVIEW

**Comment by samwgoldman** [comment]
The build also hangs on autocomplete for me locally.

**Comment by mroch** [comment]
appears to be all server commands, autocomplete is just the first test to run.

it looks like the server creates the socket and the client (at least tries to) writes the build ID to it, but the server stays blocked on the Unix.select in `serverFunctors.ml`

**Comment by mroch** [comment]
blames to https://github.com/facebook/flow/commit/af9a76888eec8262f250f68d8ae535769d51128e, but i'm not sure which part

**Comment by mroch** [comment]
#758 fixes the hanging

**Pull request closed without merging**
