### PR TITLE
[WIP] Dynamic Import Syntax Support

### LINKED ISSUE #2968: Support parsing dynamic import() syntax
Now that [dynamic import](https://github.com/tc39/proposal-dynamic-import) is stage 3 and Webpack 2 will support it for code splitting ([link](https://github.com/webpack/webpack/issues/3098)), flow-parser should correctly parse its syntax.

There's a [PR](https://github.com/estree/estree/pull/137) to ESTree to specify this new syntax.

### PR DESCRIPTION
**Pull request by deecewan**
I have no idea why I thought this would be easy.  I have not written/seen OCaml before, so I just had a crack.  It does not pass the test I've added.

Looking for a bit of advice as to where to go from here.  I'm kinda stuck at this point if we're honest.  My train of thought was 'Look at the estree definition and try and find similar examples in the code base'. That's where the train ended 🚂.

This adds support for [dynamic import syntax](https://github.com/estree/estree/blob/master/experimental/import-expression.md), which makes Flow support Webpack 2's code splitting, etc.  Attempts to fix #2968

### CODE REVIEW

**Comment by deecewan** [comment]
hmmm.  interesting.  I have signed the CLA.

**Comment by avikchaudhuri** [comment]
I'm not very familiar with dynamic imports, @jeffmo is this something on your radar?

**Comment by jeffmo** [comment]
Yea, I can run through this this week

**Comment by jeffmo** [comment]
It looks like this goes for syntax support but it doesn't hit the typechecker portions.
So I'll pick this up where you left off and try to get something out in the next few days

Thanks for getting the ball rolling!

(I'm going to leave this PR open while I iterate on things)

**Comment by deecewan** [comment]
thanks @jeffmo. I had literally no idea what I was doing, so I'd be keen to see the diff once you're done.

**Comment by jeffmo** [comment]
@deecewan: Just landed things over here: https://github.com/facebook/flow/commit/25e89d84fcd421644bf99045d4fc8ef0be448df9

It looks like we haven't cut the v0.45 release branch yet either, so should hopefully make it into that release

**Comment by deecewan** [comment]
Nice! Thanks a bunch for fixing that up.

**Comment by andreiglingeanu** [comment]
Great news!

**Comment by Diokuz** [comment]
Works with `0.46.0`

**Pull request closed without merging**
