### PR TITLE
type_parser.ml's `properties` algorithm

### PR DESCRIPTION
**Pull request by popham**
* Flow parser currently accepts `declare class K { static }`, `declare class K { static + }`, `declare class K { static - }`, `declare class K { + }`, and `declare class K { - }` without error. This PR fixes.
* This PR allows the Flow parser to recover from bad entries by skipping forward to the next T_SEMICOLON or T_COMMA.
* For object types with a static entry, an error, this PR toggles the AST's `static` member to false.

### CODE REVIEW

**Comment by popham** [comment]
I'm done touching it. I swear.

**Comment by popham** [comment]
Running `time` over

```sh
for i in $(seq 5)
do
  ./run_tests.js
done
```

master branch:
```
real     0m43.956s
user     0m29.924s
sys      0m0.754s
```

PR branch:
```
real     0m44.551s
user     0m30.519s
sys      0m0.931s
```

**Comment by popham** [comment]
Running `time` over

```sh
for i in $(seq 5)
do
  ./run_tests.js
done
```

(and piping stdout to /dev/null)

master branch:
```
real     0m8.663s
user     0m10.469s
sys      0m0.232s
```

PR branch:
```
real     0m8.618s
user     0m10.418s
sys      0m0.210s
```

**Comment by gkz** [comment]
Errors in latest version

**Pull request closed without merging**
