### PR TITLE
[flow] declare Array.fill()

### PR DESCRIPTION
**Pull request by davidye**
Declare es6 Array.fill:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

### CODE REVIEW

**Comment by istarkov** [comment]
+1

**Comment by istarkov** [comment]
Also i have a question,
is any way to add fill definition locally to Array<T> type until this pull request accepted?

**Comment by jamesgpearce** [comment]
You'll need to up date the test .exp files to match the actual output now the line numbers have changed :(

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by mroch** [comment]
i updated the tests and made `begin` and `end` optional. thanks!

**Pull request closed without merging**
