### PR TITLE
Add mixins and implements printers

### PR DESCRIPTION
**Pull request by goodmind**

### CODE REVIEW

**Comment by panagosg7** [comment]
Thanks for filling in these cases @goodmind !

Would you mind adding your tests in https://github.com/facebook/flow/blob/master/src/parser_utils/output/__tests__/js_layout_generator_test.ml instead of the suggest command. While `flow suggest uses this generator its output is not closely monitored and will probably soon move to a diff-based output.

**Comment by goodmind** [comment]
How to run them?

**Comment by panagosg7** [comment]
Just checked and this currently not possible. Will be possible soon though. I'll import and add the tests myself.

**Comment by mroch** [comment]
it's possible to run _some_ of the tests now with `make ounit-tests`, or to run just this test:

```
make _build/src/parser_utils/output/__tests__/parser_utils_output_tests.native
_build/src/parser_utils/output/__tests__/parser_utils_output_tests.native
```

I also had to manually install ounit so I guess we need a `"ounit" {test}` or whatever in `opam`.

this also affects the signature generator, which is tested by src/typing/__tests__/, which can't run the tests externally yet. still need to do some fixing to unblock this...

**Pull request closed without merging**
