### PR TITLE
F# pipeline operator

### PR DESCRIPTION
**Pull request by goodmind**
Discussion: #5443 

- [x] `await` parsing
- [x] arrow body parsing
- [x] `.flowconfig` option

### CODE REVIEW

**Comment by goodmind** [comment]
Well, it's actually looks like I implemented `minimal`, not `F#`

**Comment by goodmind** [comment]
image

**Comment by goodmind** [comment]
I ended up implementing typechecking as well 😀

**Comment by goodmind** [comment]
Babel PR https://github.com/babel/babel/pull/9450 for reference

**Comment by goodmind** [comment]
Well, there's already was function body parsing in `assignment_cover`, so I just copy-pasted it

**Comment by goodmind** [comment]
I don't think it's possible to implement all three in Flow, because there isn't such thing as parser plugins. Flow just parses everything and then errors on wrong things with `PseudoParseError`

**Comment by goodmind** [comment]
@mAAdhaTTah What you think? Is this still too early?

**Comment by mAAdhaTTah** [comment]
Probably. I don't know the Flow team's policy around this sort of thing. I know TS won't implement anything until stage 3, especially after the pain they've had with decorators. 

I'll point out that the committee isn't necessarily sold on the operator at all and there is a significant contingent who prefer the bind operator. Not only are we risking implementing the wrong version of the operator, we're risking the syntax not advancing and needing to rip it out.

**Comment by goodmind** [comment]
Well, Flow supports nullish coalescing, and optional chaining, but they're still stage 2

**Comment by goodmind** [comment]
@mAAdhaTTah I thought bind operator was dropped in 2015 and always was stage 0?

**Comment by mAAdhaTTah** [comment]
AFAIK, Bind is still Stage 1, but it's stalled out. However, we have gotten suggestions, including from committee members, about bind: https://github.com/tc39/proposal-pipeline-operator/issues/110 and https://github.com/tc39/proposal-pipeline-operator/issues/107 so I'm still viewing it as a competing proposal.

**Comment by SamChou19815** [comment]
Closing since the PR has too many merge conflicts, and we do not plan to implement proposals before stage 3

**Pull request closed without merging**
