### PR TITLE
Support JSON files with toplevel arrays

### PR DESCRIPTION
**Pull request by jeffmo**
There are plenty of JSON files in the wild (on npm, etc) that start with an array at the toplevel. This is a source of some moderate number of JSON file parsing errors that I've seen.

This fixes the json-parser function to handle both toplevel objects and arrays.

### CODE REVIEW

**Comment by mroch** [comment]
the test failures are legit

**Comment by zertosh** [comment]
This is great! But why not cover all the data types that can be toplevel values? string, number, boolean, null ?

**Comment by mroch** [comment]
@zertosh see #1420, we're going to do that

**Comment by zertosh** [comment]
Sorry, I missed that. Thanks!

**Pull request closed without merging**
