### PR TITLE
Add LanguageClient-neovim and coc.nvim plugins to editors/vim page

### PR DESCRIPTION
**Pull request by antonk52**
Since flow is an important tool in modern development it should be extremely reliable and efficient. The official `vim-flow` plugin seems to be abandoned. The last commit was in December 2017. I believe the official docs should note `LanguageClient-neovim` which allows us to efficiently look up types under cursor.

### CODE REVIEW

**Comment by ApolloTang** [comment]
@antonk52  Some of us is not using neovim, flow-vim is still relevant.

**Comment by ApolloTang** [comment]
@antonk52 my apology, LanguageClient-neovim also support vim.

**Comment by antonk52** [comment]
The name is pretty counter intuitive. I believe at first this plugin only supported neovim but now it works with both neovim and vim.

**Comment by antonk52** [comment]
I agree that flow-bin and LanguageClient-neovim are not the same thing. If we look at the current flow-vim readme we will learn that it is used to provide autocomplitions and to check for errors. The former can be also done with ALE which is currently mentioned on the website. If we dig deeper in the readme we will also learn that it can be used to look up types under the cursor, I believe it to be a primary reason one would install a plugin for flow support. This is done a lot more efficiently by LanguageClient-neovim plugin. I think that with provided sensible defaults it is fairly straight forward to get started. Specially for a vim user ¯\_(ツ)_/¯ As for autocompletion it is probably beneficial to have deoplete + ternjs duo since you will get a nice autocompletion for the whole project including types.

If you disagree I can return vim-flow to its previous position with addition of LanguageClient-neovim. It is also should be noted that it works with vim. vim-lsp and vim-lsc will be there too =)

**Comment by ApolloTang** [comment]
@antonk52 just discover this [https://github.com/neoclide/coc.nvim](https://github.com/neoclide/coc.nvim)

a comparison btw LanguageClient-neovim and coc is here  https://github.com/neoclide/coc.nvim/issues/454#issuecomment-465441127

**Comment by nmote** [comment]
This seems reasonable to me, but I'd like to get @gabelevi's thoughts since it looks like he is the one who was most recently involved in vim-flow.

**Comment by antonk52** [comment]
Personally I am all up for improving and gathering all alternatives in one place.

Last night I tried to get coc.nvim working with my set up, but was unsuccessful. Not sure if a set up with an external config is a vim like, but that's a different story. There is a [way](https://github.com/neoclide/coc.nvim/issues/418#issue-408463213) to keep all your settings in vimrc but besides this issue I wouldn't get to know this by looking at the docs. I'm up for adding coc.nvim to the docs but think that someone who actually uses it would be a better fit to add it in order to provide minimum set up to get it up and running.

**Comment by ApolloTang** [comment]
@antonk52, I am very happy w coc, it is the best one I have tried so far. I feel now vim has an lsp support like that in VS code or jetbrain. 

btw, i haven't installed the flow extension, does it works for you ?

**Comment by antonk52** [comment]
@ApolloTang I've used `coc.nvim` for two days now and I have to say that I am impressed with the speed. I've extracted the minimal coc settings to get started with flow in a [gist](https://gist.github.com/antonk52/4587b2687268a5dde494240ce975a708) (no `coc-settings.json` needed). I'll add `coc.nvim` to this PR. The auto fix functionality for eslint is way speedier even comparing it to ALE.

I have not set up the auto completion since I am pretty happy with deoplete atm.

Please let me know if anything else should be added to this PR.

**Comment by ApolloTang** [comment]
@antonk52 for your reference here is my minimum set setup:
https://github.com/ApolloTang/vim-sandbox/tree/master/0500-coc/01-coc-minimum


I found out that there isn't a coc-flow extension yet so I configured my flow LSP in coc-settings.json: 
https://github.com/ApolloTang/vim-sandbox/blob/master/0500-coc/01-coc-minimum/project-flow/.vim/coc-settings.json

My flow configuration is per project basis because i need to turn off typescript lsp when i am in flow project folder.

**Comment by ApolloTang** [comment]
@antonk52,  Finally if you would put back vim-flow as an non lsp option, i think your change would be super great !!

**Comment by antonk52** [comment]
I've updated my branch with `vim-flow` and preserved the original anchors so older links will still take people to the appropriate sections. I am also going to rename this PR to be more accurate.

**Comment by nmote** [comment]
I'm not familiar with this setup and was hoping to get @gabelevi's input, but I'll trust that what you've done here is an improvement. Others can always submit update PRs later if they find inaccurate info. Thanks for your contributions.

**Comment by nmote** [comment]
Unfortunately there are now some merge conflicts. If you address those, I will review this promptly.

**Comment by nmote** [comment]
I also built the site and the formatting is broken. Could you take a look and fix the formatting?

**Comment by antonk52** [comment]
hi, I've fixed the formatting and have updated the branch but not sure why ci is still failing.

**Comment by nmote** [comment]
Our CI is flaky -- I'll take a look

**Pull request closed without merging**
