### PR TITLE
Correct function and object names

### PR DESCRIPTION
**Pull request by MichalZalecki**

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mroch** [comment]
oops, good catch

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/205292153205370/int_phab) to review.

**Pull request closed without merging**
