### PR TITLE
Update 01-functions.md with ES2015 function features [Ref #560]

### PR DESCRIPTION
**Pull request by jrajav**
Add information about annotating ES2015 default values and arrow functions (based on current behavior) to the Functions docs.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by bhosmer** [comment]
@jrajav Thanks Jonathan!

@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1563559903950534/int_phab) to review.

**Pull request closed without merging**
