### PR TITLE
Add hints to property read error messages

### PR DESCRIPTION
**Pull request by goodmind**
image
image

### CODE REVIEW

**Comment by nmote** [comment]
If you rebase, I'll review! Sorry this didn't get any attention earlier.

**Comment by goodmind** [comment]
@nmote how can I run `ocamlformat` first?

**Comment by goodmind** [comment]
It's probably easier to just make new branch

**Comment by nmote** [comment]
@goodmind what we've done is this:

* Rebase to the commit right before the ocamlformat application.
* Rebase onto the ocamlformat commit while telling Mercurial to resolve all conflicts by taking the changes from the commit being rebased.
* Run ocamlformat over the result.

I'm sure there is a Git equivalent to the second step.

**Comment by gkz** [comment]
We have had such hints for a while (I think since 0.120?). Closing

**Pull request closed without merging**
