### PR TITLE
Improved typing of the synthetic events

### PR DESCRIPTION
**Pull request by HenriBeck**
- Improved typing of the nativeEvent
- Improved typing of the SyntheticTouchEvent
- Improved typing of the getModifierState function

### CODE REVIEW

**Comment by mrkev** [comment]
Hello, can you include some documentation backing up your changes? From like MDN, w3, etc?

**Comment by HenriBeck** [comment]
Yes, of course.

#### Improved typing of the SyntheticTouchEvent

As described in the [React Docs](https://reactjs.org/docs/events.html#touch-events) the `touches`, `changedTouches ` and `targetTouches` are DOMTouchLists. [](url)

#### Improved typing of the getModifierState function

The React Docs describe the `getModifierState` property as a function which takes a key and returns a boolean. 

https://reactjs.org/docs/events.html#mouse-events
https://reactjs.org/docs/events.html#touch-events
https://reactjs.org/docs/events.html#keyboard-events

#### Improved typing of the nativeEvent

This is a refinement. It now uses a specific DOM Event rather than a generic one.

**Comment by mrkev** [comment]
sweet thanks!

**Comment by mrkev** [comment]
Getting lots of type errors from this. Could you test and fix when you have a chance?

**Comment by HenriBeck** [comment]
Yes, I will check them out tomorrow.

**Comment by frontendphil** [comment]
Would it be possible to extend that to all those `SyntheticSomethingEvent` types? I'm currently looking at a type error for `SyntheticKeyboardEvent` where the `nativeEvent` is just `Event` instead of `KeyboardEvent`.

**Comment by HenriBeck** [comment]
@frontendphil yes, I added the actual native event where it is possible.

@mrkev The appveyor build fails for some reason, but my local build passed all of the tests. There seems to be an issue with linking.

**Comment by mrkev** [comment]
Dw about the appveyor, it's been broken and being looked into I think

**Comment by HenriBeck** [comment]
@mrkev any updates on this?

**Comment by nmote** [comment]
I'll take a second look at this

**Comment by nmote** [comment]
It looks like the change to `SyntheticDragEvent`'s superclass is incorrect. In the docs, it's grouped with mouse events. Could you justify this change further, or revert the change? Could you also double-check the change to `SyntheticWheelEvent`'s superclass?

Once you do that I'll take a closer look

**Comment by nmote** [comment]
Closing, as I have heard anything in a little while. Feel free to reopen if you are still interested. See also #7587

**Pull request closed without merging**
