### PR TITLE
fetch API: body can be ArrayBuffer or ArrayBufferView as well

### PR DESCRIPTION
**Pull request by philikon**
See https://fetch.spec.whatwg.org/#bodyinit and https://heycam.github.io/webidl/#BufferSource

### CODE REVIEW

**Comment by philikon** [comment]
Ping?

**Comment by philikon** [comment]
Ping???

**Comment by jeffmo** [comment]
@philikon: Very sorry, I dropped the ball here. I'm working on getting this merged now.

**Comment by philikon** [comment]
Thanks much @jeffmo!

**Pull request closed without merging**
