### PR TITLE
Update react-dom/server

### PR DESCRIPTION
**Pull request by marudor**
Add streaming API.
Also added the version string.

### CODE REVIEW

**Comment by mrkev** [comment]
Could you link to some sort of docs that verify this is correct?

**Comment by marudor** [comment]
https://reactjs.org/docs/react-dom-server.html#rendertonodestream

**Comment by mrkev** [comment]
I don't see any reference to the version string, can we confirm in exists or remove it from the PR?

**Comment by marudor** [comment]
image

**Pull request closed without merging**
