### PR TITLE
fix all DOM return type of getBoundingClientRect() & getClientRects()

### PR DESCRIPTION
**Pull request by ryota-murakami**
# Overview
In https://github.com/facebook/flow/commit/699ac4e99514337370a9ce19e288c21834747a1e I fixed about `DOMRect` and `DOMRectList`.

Even though I've just noticed that commit wasn't enough.
That fix is only applied to `class TextRange` without other DOMs which has `getBoundingClientRect()` & `getClientRects()` methods.

This PR is additional work for I missed in https://github.com/facebook/flow/commit/699ac4e99514337370a9ce19e288c21834747a1e

Thanks!

### CODE REVIEW

**Comment by ryota-murakami** [comment]
@fishythefish Could you please review? it's not urgent though.
I  wish `getBoundingClientRect()` of all Object typing properly in my source code.

Feel free to close this PR if you don't think it's useful😀

**Comment by nmote** [comment]
Could you link API docs which support this change?

**Comment by ryota-murakami** [comment]
@nmote Sure, W3C spec is here.
https://drafts.fxtf.org/geometry/#domrectreadonly

**Comment by nmote** [comment]
I'm not familiar with that site -- do I understand correctly that this is still in the early stages of development? The `drafts` subdomain makes me a bit suspicious 😄 

We usually don't take in-development features until they are pretty stable and have a good shot of making it into the standard. Can you help me understand how far along this is?

**Comment by ryota-murakami** [comment]
@nmote I'm sorry I didn't explain clear enough. 
The `draft` [was referred by prev PRs reviewer.](https://github.com/facebook/flow/pull/6885#discussion_r219613831)


You know, I know that feeling, it's draft! 
even though the draft text is same as MDN doc and today's chrome returning a `DOMRect` object.
So I didn't mention it before.

・MDN doc `Element.getBoundingClientRect()
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

・I Just saved chrome console screenshot

screen shot 2019-02-12 at 17 27 22


Fortunately that fact is easy to confirm `getBoundingClientRect()` return `DOMRect`.
I've confirmed it on OSX 10.14.2(Mojave) Chrome/Safari/Firefox.

AFAIK the PR is safety and There will be a certain number of users waiting for Flow to be able to handle `DOMRect`.

thank you🙇‍♂️

**Comment by ryota-murakami** [comment]
@nmote Hello, Thank you for handle bunch of daily work 🤗
I'm not sure about this PR state still `Open`.

facebookbot say this is already imported, why not just closed?
https://github.com/facebook/flow/pull/6997#pullrequestreview-202925898

**Pull request closed without merging**
