### PR TITLE
Add "Immediate" global timer funcs to Node lib

### PR DESCRIPTION
**Pull request by tgroshon**
- add setImmediate function declaration
 - add clearImmediate function declaration

### CODE REVIEW

**Comment by tgroshon** [comment]
Done!

**Comment by jeffmo** [comment]
Nice! We can type the `callback` params as `((...args: Array<any>) => void|string` to be more specific, right?

**Comment by tgroshon** [comment]
@jeffmo Sure!  But how about just `((...args: Array<any>) => void)` because I do not think setImmediate takes a string.

https://github.com/joyent/node/blob/master/lib/timers.js
line 397

**Comment by jeffmo** [comment]
Ah, yea that's great! (I guess I got it mixed up with the weird API that browsers have for setTimeout)

**Comment by tgroshon** [comment]
This should be ready to go!

**Comment by jeffmo** [comment]
Thanks a ton, this is great

**Pull request merged**
