### PR TITLE
Files starting with dot

### PR DESCRIPTION
**Pull request by gabrielrumiranda**
This PR solve the problem of this [issue](https://github.com/facebook/flow/issues/7673). Lets you import files that start with dots

### CODE REVIEW

**Comment by gabelevi** [comment]
I'm not sure I'm comfortable with deleting this behavior. Like there's a lot of JS for me in `.hg/`. Someone could add that to their `[ignores]`, but I'd rather that the default behavior does the right thing.

I suppose I'm fine making it an option? Like if someone wants to set `ignore_dotfiles=false` in their `.flowconfig` then they're welcome to do so? You would need to modify `flowConfig.ml` to add the option and then also add it to `type options` in `files.ml`. Then the compilation errors should direct you to all the other places you need to fix.

**Comment by gabrielrumiranda** [comment]
@gabelevi I think this the better way, I go make this changes

**Comment by goodmind** [comment]
@gabrielrumiranda can you add tests with nameless files?

**Comment by gabrielrumiranda** [comment]
@goodmind I separate the test in another folders, when you tell nameless file you tell a file with name `.` ?

**Comment by goodmind** [comment]
@gabrielrumiranda yeah, like `.flowconfig`, `.js`

**Comment by gabrielrumiranda** [comment]
I'm try but don't work

**Comment by gabrielrumiranda** [comment]
Other thing, files begin with dot inside a node_module cannot be import using relative path. I test this in a simple node.js project and don't work too

**Comment by goodmind** [comment]
Hmm

**Comment by goodmind** [comment]
@gabrielrumiranda it should work now

**Pull request closed without merging**
