### PR TITLE
Tiny fix to indentation in Function delaration

### PR DESCRIPTION
**Pull request by liamgriffiths**
This was buggin me a little bit 😂

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by gabelevi** [comment]
Ha! Thanks for cleaning it up! I'll merge as soon as you sign the CLA :)

**Comment by liamgriffiths** [comment]
Cheers - should be all good

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gabelevi** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1012762622126970/int_phab) to review.

**Pull request closed without merging**
