### PR TITLE
Add type definitions for Object.entries and Object.values

### PR DESCRIPTION
**Pull request by ianobermiller**
Add type definitions for Object.entries and Object.values. See a test here:

http://tryflow.org/#5d9b08200a09cd3b88cae9fc59b5045b

### CODE REVIEW

**Comment by ianobermiller** [comment]
Need to add tests and update all the broken ones, look at https://github.com/facebook/flow/commit/e8f7451c33b4c4bb078b4c230621cd74d9e2f29e.

**Comment by samwgoldman** [comment]
For `Object.entries`, even if I pass an object w/ a dictionary type having a non-string key, the return type should still use `string` as the 0th element of the tuple in the array—the key is still a string at runtime, after all.

Also, the idea that you can pass an object with type `{ foo: string, bar: number }` into a context expecting a dict `{ [k:any]: string|number }` should be legal. (See #1338). However, these type defs rely on that unsound behavior. I'm working on a commit to fix the bug, but that fix will also break these defs, so comprehensive tests are key to make sure we preserve the intended behavior.

**Comment by samwgoldman** [comment]
Here are some test cases:

```javascript
type A = { foo: string, bar: number };
type B = { [k: number]: boolean };

var values = Object.values;
var entries = Object.entries;

declare var a: A;
declare var b: B;

// Sealed, non-dict object types

// OK
(values(a) : Array<string|number>);

// error: array type ~> void
(values(a) : void);

// error: string ~> void, number ~> void
(values(a) : Array<void>);

// OK
(entries(a) : Array<[string|number, string|number]>);

// error: array type ~> void
(entries(a) : void);

// error: tuple type ~> void
(entries(a) : Array<void>);

// error: string ~> void, number ~> void
(entries(a) : Array<[void, string|number]>);

// error: string ~> void, number ~> void
(entries(a) : Array<[string|number, void]>);


// Dictionary types

// OK
(values(b) : Array<boolean>);

// error: array type ~> void
(values(b) : void);

// error: boolean ~> void
(values(b) : Array<void>);

// OK
(entries(b) : Array<[string, boolean]>);

// error: number ~> string
(entries(b): Array<[number, boolean]>);

// error: array type ~> void
(entries(b) : void);

// error: tuple type ~> void
(entries(b) : Array<void>);

// error: string ~> void
(entries(b) : Array<[void, boolean]>);

// error: boolean ~> void
(entries(b) : Array<[string, void]>);
```

**Comment by samwgoldman** [comment]
Ping? I can get this one across the finish line for you, if you don't have time.

**Comment by ianobermiller** [comment]
@samwgoldman Thanks, yes please feel free to do so. I just started a war room yesterday, so no spare time at the moment.

**Comment by ianobermiller** [comment]
Thanks, Sam!

**Comment by casertap** [comment]
I am having a similar problem
my code look like this
````
class FacetQuery {
  solrFieldName: string;
  facetQueryKey: string;
  facetQueryValue: number;
  constructor(k: string, v: number) {
    this.solrFieldName = k.split(':')[0];
    this.facetQueryKey= k;
    this.facetQueryValue= v;
  }
}

export default class FacetQueries{
  facetQueries: Array<FacetQuery>;
  constructor(facet_queries: {string: number}){
    const entries: Array<[string, number]> = Object.entries(facet_queries);
    this.facetQueries = entries.map(([k, v]) => {
      new FacetQuery(k, v);
    });
  }

````
I get this error
````
[0] src/domain/facet/FacetQueries.js:22
[0]  22:     this.facetQueries = (entries(facet_queries) : Array<[string, number]>).map(([k, v]) => {
[0]                               ^^^^^^^^^^^^^^^^^^^^^^ function call
[0]  22:     this.facetQueries = (entries(facet_queries) : Array<[string, number]>).map(([k, v]) => {
[0]                                                                       ^^^^^^ number. This type is incompatible with
[0]  37:     static entries(object: any): Array<[string, mixed]>;
[0]                                                      ^^^^^ mixed. See lib: /private/tmp/flow/flowlib_35940e29/core.js:37
````
my actual facet_fields object will look like this
````
"facet_fields": {
      "postTypeId": [
        "2",
        8237,
        "1",
        6376,
        "5",
        36,
        "4",
        30
      ]
    },
````
I tried 
````
const entries: Array<[string, number]> = Object.entries<number>(facet_queries);
```
but this is not a valid syntax
Can anyone help solving this, please ?

**Comment by ianobermiller** [comment]
@samwgoldman You reverted this change to `Object.entries` and `Object.values` in https://github.com/facebook/flow/commit/731a3f9d908845e8854353edb248b68f63627f14. Was that intentional, and if so, is it necessary?

**Pull request closed without merging**
