### PR TITLE
Support custom promises

### PR DESCRIPTION
**Pull request by vkurchatkin**
@avikchaudhuri there is still a problem with union

### CODE REVIEW

**Comment by bhosmer** [comment]
Thanks Vladimir!

**Comment by bhosmer** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-2** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3755894) to review internal test results.

**Comment by vkurchatkin** [comment]
@bhosmer @mroch I've noticed that this PR has been reverted, can you share the details?

**Pull request closed without merging**
