### PR TITLE
Added aarch64 job in CircleCI

### LINKED ISSUE #7556: Support for arm64 architecture
Dear Team,

We were able to build the flow package for aarch64(arm64) architecture and generate flow binary.

Need flow-bin to execute packages like preact, chalk, graphql and many more packages in arm64 platform, as there is no existing binary in releases to download for arm64 platform all these packages are failing in arm64 platform.

Please guide me to get flow in the official aarch64 repository and in releases link i.e. https://github.com/facebook/flow/releases/.

Thanks in advance.

Regards,

### PR DESCRIPTION
**Pull request by odidev**
@mroch ,

Added aarch64 job using executor type machine in CircleCI config file and related Dockerfile and build script. AArch64 flow binary is created and stored as an artifact. 

Tested in my local CircleCI environment. AArch64 flow binary can be downloaded and verified from [here](https://89-274139798-gh.circle-artifacts.com/0/flow-linux-aarch64.zip).

Closes #7556.

Please review and let me know if any changes required.

### CODE REVIEW

**Comment by odidev** [comment]
@jamesisaac / @mroch ,

I have added an AArch64 job in CircleCI as suggested in #7556. Can you please review the changes and let me know if any changes required?

This will help to run flow binaries in the ARM64/AArch64 platform, which is required in many node packages like preact, chalk, graphql, vue etc..

Thanks.

**Comment by odidev** [comment]
Can you please review and provide feedback?

**Comment by odidev** [comment]
@mroch / @jamesisaac,
I have rebased and added aarch64 check for CCFLAGS in Makefile as '-mcx16' flag is not supported in aarch64 and added the commit.

Please review and let me know if any changes required.

**Comment by jamesisaac** [comment]
(I'm not part of the Flow team myself and would not be able to help getting this merged - not sure the reason for the tag.  If you are having trouble getting the attention of anyone on the Flow team, you might want to try the Discord linked in the Readme.)

**Comment by odidev** [comment]
> (I'm not part of the Flow team myself and would not be able to help getting this merged - not sure the reason for the tag. If you are having trouble getting the attention of anyone on the Flow team, you might want to try the Discord linked in the Readme.)

Thanks @jamesisaac for the reply. Sure, will try Discord.

**Comment by rhenwood-arm** [comment]
Is there any progress on this ticket? I would be great to see a Flow binary for AArch64 as there are a bunch of project that depend on it.

**Comment by lesar** [comment]
I'm just writing a new project on rpi4.  
How much time will be necessary to merge this release on new stable version?  

best regards,
Leonardo

**Comment by STRML** [comment]
This blocks use of Flow on Apple Silicon (Rosetta 2 does not work due to #8538). Please merge @mroch.

**Comment by delprofundo** [comment]
Can we please merge this? this is our last outstanding dependency that wont work with rosetta.

**Comment by jaimeagudo** [comment]
Please merge 🙏 @mroch

**Comment by odidev** [comment]
@mroch,

Can you please review the changes and let me know if any changes required?

This will help to run flow binaries in the ARM64/AArch64 platform, which is required in many node packages like preact, chalk, graphql, vue etc..

This is a blocker for many projects.

Thanks.

**Comment by lesar** [comment]
I'm new to flow and I need to start flow on rpi4.
I like flow comment to write in pure javascript.  
Any expectation for new build on arch ARM64/AArch64?

best regards,
Leonardo

**Pull request closed without merging**
