### PR TITLE
Fix autocomplete for generic type aliases

### PR DESCRIPTION
**Pull request by vkurchatkin**
Fixes https://github.com/facebook/flow/issues/2967

### CODE REVIEW

**Comment by UnsungHero97** [comment]
Any update on when this will be merged?

**Comment by maoueh** [comment]
Sorry to disturb, could we get some attraction for merge here. It seems a fairly easy fix and it make it harder to play with RxJs for example when defining specific type aliases.

**Comment by TrySound** [comment]
Ping guys

**Comment by mvitousek** [comment]
It looks like sometime in the last year we fixed this issue by another approach, or at least the test you suggested is passing now (modulo line numbers). I'll go ahead and merge just the test from this PR, sorry we didn't get to it sooner. If this problem is actually persisting in a way that isn't captured by this test case, please let me know and I'll take another look.

**Pull request closed without merging**
