### PR TITLE
lib: Improve Object.values and Object.entries

### PR DESCRIPTION
**Pull request by zertosh**
Use `$Keys` and `$Values` to better reflect that actual types of `Object.values` and `Object.entries`. Fixes #2804.

### CODE REVIEW

**Comment by vkurchatkin** [comment]
This is really unsound in general.

**Comment by zertosh** [comment]
@vkurchatkin how so?

**Comment by vkurchatkin** [comment]
Because $Keys and $Values return statically known properties, while an object might have more properties at runtime.

**Comment by TrySound** [comment]
@vkurchatkin Which ones? Prototype is not handled.
> The Object.keys() method returns an array of a given object's own enumerable properties, in the same order as that provided by a for...in loop (the difference being that a for-in loop enumerates properties in the prototype chain as well).

**Comment by samwgoldman** [comment]
Vladimir is right. There are two issues.

Width subtyping:

```
var o: { p: number, q: string } = { p: 0, q: "", foo: "foo" };
var keys: "p" | "q" = Object.keys(o); // lies
var vals: number | string = Object.values(o); // lies
```

Proto vs. own

```
var o: { p: number, q: string } = Object.create({ p: 0, q: "" });
var keys: Array<"p" | "q"> = Object.keys(o); // lies
var vals: Array<number | string)> = Object.values(o); // lies
```

Exact object types are great for the former case, because they by definition exclude values having more properties. For the latter case, we really need to provide better mechanisms to specify object layout as part of types, since so many APIs depend on it. It's on our radar.

Closing this because the implementation is unsound in a way that I'm not comfortable with. I think if we can continue wearing the hair shirt for a bit longer we can come up with some useful+principled solutions to make idiomatic code pass with simple types.

Thanks!

**Pull request closed without merging**
