### PR TITLE
Attempt to show Flow rules firing with a GIF.

### PR DESCRIPTION
**Pull request by winkler1**
The docs at http://flowtype.org/docs/react.html are fairly subtle in understanding how state types are checked. This is an attempt to show it visually.

Used default compression settings from gifify, could redo if needed.

### CODE REVIEW

**Comment by jeffmo** [comment]
Sweet! Could we put it after the code block?

(i.e. give readers a chance to read the code in nice static form, then see the gif animation as they scroll past)

**Comment by winkler1** [comment]
@jeffmo Sure - moved it to the following markup block. Hope that looks OK, am not able to preview...

**Comment by winkler1** [comment]
Rebased and squashed..

**Comment by winkler1** [comment]
@jeffmo Does this look OK?

**Comment by jeffmo** [comment]
@facebook-github-bot shipit

**Comment by jeffmo** [comment]
Sorry, didn't see you'd updated this! Looks good to me

**Pull request closed without merging**
