### PR TITLE
Added TouchEvent, TouchList & Touch declarations

### PR DESCRIPTION
**Pull request by dj-foxxy**
Hi just started using Flow. It's really good: whole families of bugs have been caught. I've added touch event stuff to dom.js. Happy to take feedback. Not sure about TouchList#item(), see comments in commit. Thanks.

### CODE REVIEW

**Comment by dj-foxxy** [comment]
Looks like I need to regenerate the expected output from the DOM test because my additions have changed the line numbers.

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gabelevi** [comment]
Looks good to me! Importing...

**Comment by gabelevi** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/194220947642475/int_phab) to review.

**Pull request closed without merging**
