### PR TITLE
parser: add parse-only support for "import.meta"

### LINKED ISSUE #6913: Flow parser should support import.meta
`import.meta` is a stage 3 proposal that has shipped in Chrome, Firefox, and Node 10. Flow should be able to parse this syntax.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcA6LAU0IENiBXfGAbiA

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
Resolves #6913. As with `new.target`, we can parse the expression, but
we fail to typecheck it. Clients can use a suppression comment to ignore
uses of `import.meta` in an otherwise valid file.

The parse error message on inputs like `import.notMeta` was chosen to be
consistent with the message emitted by Babylon.

Test Plan:
Unit tests added, and all existing tests pass.

wchargin-branch: parse-import-meta

### CODE REVIEW

**Comment by goodmind** [comment]
@mroch is this still on your radar?

**Comment by goodmind** [comment]
@mroch

**Comment by fredericgermain** [comment]
@mroch

**Comment by wchargin** [comment]
I went ahead and merged in changes over the last year, fixed conflicts,
upgraded past a major OPAM and OCaml version boundary, installed `bwrap`
from source after finding all its dependencies, revised the code due to
some changes in Flow internals, and added a new test. @mroch, it’d be
great if this could be landed so that I don’t have to do this all again
next year! :-)

**Comment by wchargin** [comment]
![Bernie Sanders meme: “I am once again asking for your code review”][meme]

Happy birthday! This pull request is two years old. As such, I’ve again
resolved the merge conflicts due to upstream changes, and gotten the
tests passing. @jbrown215, it’d be great if this could be landed so that
I don’t have to do this all again again next year! :-)

[meme]: https://user-images.githubusercontent.com/4317806/94964153-2bc3b980-04ae-11eb-8cd3-a6721066d170.png

**Comment by fredericgermain** [comment]
You're so brave @wchargin 

This issue is the reason I'm going to TypeScript.

I thought Flow was a better idea overall than TypeScript, but the latest versions and the governance of the project made me lose trust in it.

Happy birthday to the issue!

**Comment by jbrown215** [comment]
From @mroch: 

> I don't think the locs are correct in the error cases, they consume tokens that aren't included in the range and don't point at the entire error (AFAICT).
IMO, should still use with_loc but also grab start_loc if it's needed for that error_at call.

The lint errors are ocamlformat errors. I can fix that on my side!

**Comment by FezVrasta** [comment]
Any chance to get this PR merged?

**Comment by TrySound** [comment]
Hi @jbrown215 @mroch! Any new on this feature?

**Comment by ancms2600** [comment]
Get it merged, you turkeys

**Comment by isker** [comment]
Bless.

**Comment by gkz** [comment]
@ancms2600 
> Get it merged, you turkeys

There you go
🦃

**Comment by FezVrasta** [comment]
Is there any way to type `import.meta.env`?

**Comment by gkz** [comment]
What should that be? Do you have links to documentation?

**Comment by FezVrasta** [comment]
It's used by Vite to access environment variables.

**Comment by gkz** [comment]
If I add a `[string]: mixed` indexer to the type, so you can access random other properties (but they're mixed so you have to refine them first to e.g. a string), would that be fine? We probably don't want to hardcode random specific things like vite env vars in Flow.

So you could do

```
const env = import.meta.env;
if (typeof env === 'string') {
  // do the stuff
}
```

**Comment by FezVrasta** [comment]
I think it would be fine, anyways most of the times all you do is doing a string comparison so even if it's mixed it will work just fine.

Of course having a way to extend such types in user land would be optimal, as import.meta is thought to be user extensible.

**Pull request closed without merging**
