### PR TITLE
Fix libdef for AudioContext

### LINKED ISSUE #4798: Fix libdef for AudioContext
Hi guys,

I just noticed that AudioContext is not correctly defined. Regarding the [documentation](https://developer.mozilla.org/de/docs/Web/API/AudioContext/createMediaStreamSource) it accepts a MediaStream as parameter. However this parameter definition is missing in your [class declaration for AudioContext](https://github.com/facebook/flow/blob/v0.54.0/lib/bom.js#L654).

Reproduce bug and hotfix: [Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAQQFcMBLOAYTgDsAXLADw7AG9UYUsXxcAslkb4Ayh1EBbGXFqEcWABQKAnnMUAuMJOl6s+BQEpDxhrPlmFdRnGWr1AOTjYA3EJFmuajZ8GG1yLEINKxpg0PDCTx9UAF90VGBgMAAFOFCoBhgYUgJKMGx8tgYOJjZUBAY2DEQAOicmVk4ePgBeMA16xpa2lnYuXjAAHwmwAaaEZoQsACMAayrhjrG+KZmGueaFOAAvDdGuyenZlrhTzvGdq-mFcluti3QcdnI+cI5aAAcADIMb5YNgRMC9DTfAxGKS2UzmCyQgB8Aj8nzY3zA+Ho7TOvEMr3OvXBSEerTxIzuHCiGK+fHwsTCESJzPiiRIvVxzk2XWaOFEgXZETpwkx2IUDEFcH+AAt2FhrPC7Iphq41FhOZCcVS+bwBUKsDZVQ4NepofYkX5QGBmvbkGhkkA)

Greetings,
Thomas

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #4798

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@samwgoldman I think this one can be merged? 🙂

**Comment by MichaelDeBoey** [comment]
@samwgoldman @asolove Any news on this one? I think this one can be merged?

**Comment by gre** [comment]
please accept this 🙏

**Comment by MichaelDeBoey** [comment]
Only the AppVeyor build seems to fail.
Maybe a rerun will pass it, just like the Travis CI build?

CC: @asolove @samwgoldman @mroch @nmote

**Comment by mroch** [comment]
Whoops, sorry! Looks like this got fixed in https://github.com/facebook/flow/commit/469518a07adc8ae2662070f52a1e1ba7b01b5e33 which came after yours. Thanks for the fix!

**Pull request closed without merging**
