### PR TITLE
feat: add `Element.prototype.toggleAttribute`

### PR DESCRIPTION
**Pull request by keithamus**
See https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute for more.

### CODE REVIEW

**Comment by keithamus** [comment]
Any news on this? @ljw1004 @nmote?

**Comment by apsavin** [comment]
I think we need to mention @mrkev who usually saves our souls

**Comment by keithamus** [comment]
Support for `toggleAttribute` was added to Firefox 63 just the other day. This means `toggleAttribute` is supported in all modern browsers with the exception of Safari. However for my use case - Flow is now preventing me from using this. It would be fantastic to get this PR merged soon!

**Comment by keithamus** [comment]
@nmote any chance of seeing this landed soon? Edge 18 released in December with support for `toggleAttribute`. So just to recap Chrome (69), Firefox (63), Edge (18) and Opera (56) all support this.

**Comment by nmote** [comment]
Sorry for the delay. The change looks good, but could you rebase to kick the tests? You might also need to re-record the tests (look at `./tool record` and `./runtests.sh -r`). Once everything is green I will merge

**Comment by nmote** [comment]
Okay, I'll take a look

**Pull request closed without merging**
