### PR TITLE
Fix for class method default parameters that use `this`

### PR DESCRIPTION
**Pull request by jonbretman**
Example of bug - https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwxyxsAuMXAFwCcBLAOwHMqqAjACgxgAvGAYALFrgB02AJSkqFKgF9uyoA

### CODE REVIEW

**Comment by jonbretman** [comment]
Think I'm going to need some help understanding the build failure in Travis for OCaml 4.03.0 😕

**Comment by jeffmo** [comment]
The build error looks like some kind of caching problem (we seem to cache build artifacts in Travis).
I've restarted the CI build, so let's see if it goes away...

**Comment by jonbretman** [comment]
@jeffmo failed again 😿

**Comment by jeffmo** [comment]
Shooting in the dark a bit now, but what happens if you rebase?

In any case, I don't see how this would be related to your change -- but it would be nice to rule out the CI issue if possible.

**Comment by jonbretman** [comment]
@jeffmo let's find out! Rebased + pushed.

**Pull request closed without merging**
