### PR TITLE
Fix function variance

### LINKED ISSUE #7412: Variance sigils are ignored on function declaration type parameters
Flow version: 0.91.0

## Expected behavior

Flow should check that a function declaration's type parameters are used in proper positions with respect to their variance.

```JavaScript
// These type check!
function f1<+T>(x: T): mixed {}
function f2<-T>(x: T): T { return x }
```

## Actual behavior

Flow ignores variance annotations on function declarations. They do currently work in conjunction with type aliases, however:

```JavaScript
// These error, as expected.
type F1 = <+T>(x: T) => mixed;
type F2 = <-T>(x: T) => T;
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCmAzvmPgE5lxkA0YAhoaQB4AO+AxgC74AmAdKk4BPNmABiARjABeMAB4A1NgB8ACiYAuHAEoZysAFsAlk14BuQSJJiATDPkBaFeq3Zd0-dgsYseIiR44ADsAck4AQlQoAFcgriNgsCgJRWdNHS1jUx4wAG8AXyjY+MSoGzknNXS3VzywMnxOaLIgsCYwQqA

### PR DESCRIPTION
**Pull request by goodmind**
Fixes #7412

### CODE REVIEW

**Comment by goodmind** [comment]
@mroch

**Comment by mvitousek** [comment]
Looks promising, can we do the check in func_sig.functiontype instead?

**Comment by goodmind** [comment]
yeah

**Comment by goodmind** [comment]
Probably would need more tests for this

**Comment by goodmind** [comment]
@mvitousek can you import and check this?

**Pull request closed without merging**
