### PR TITLE
Implement search

### PR DESCRIPTION
**Pull request by vjeux**
Powered by the awesome Algolia :)

### CODE REVIEW

**Comment by vjeux** [comment]
I need to tweak the structure of the header a bit so that it doesn't show "Edit on Github"

**Comment by samwgoldman** [comment]
This. is. awesome.

@facebook-github-bot shipit

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by vjeux** [comment]
Oops I know what's going on, the import script doesn't know how to import binary files yet

**Comment by sdwilsh** [comment]
If you tell the bot to ship it again, I think this will work.  I imported the change manually with my fixes for binary changes so it should just land it.

**Comment by vjeux** [comment]
@facebook-github-bot shipit

**Comment by sdwilsh** [comment]
...or not.  I'll just land the change so it works in prod and then you can do this :)

**Comment by avikchaudhuri** [comment]
For posterity, can somebody explain what exactly happened here, and whether we should do anything to make things like this easier in the future? (Or not worth it?) cc @mroch

**Comment by sdwilsh** [comment]
I made things easier by fixing a bug in Facebook code that the ship it stuff uses.  See t10045016 if you are an employee.

**Comment by avikchaudhuri** [comment]
Cool, thanks!

**Pull request closed without merging**
