### PR TITLE
Added JavaScript Enhancements plugin to Sublime Text 3 editor - docs

### PR DESCRIPTION
**Pull request by pichillilorenzo**
Finally Java​Script Enhancements has been published on Package Control: https://packagecontrol.io/packages/JavaScript%20Enhancements

This is a plugin for Sublime Text 3 that uses Flow under the hood! GitHub project: https://github.com/pichillilorenzo/JavaScriptEnhancements

It offers smart javascript autocomplete, real-time errors and, also, a lot of features about creating, developing and managing javascript projects (such as React, Cordova, etc.).

Do you agree with this pull request?? Is it ok the description that I wrote?

Thanks in advance!

### CODE REVIEW

**Comment by pichillilorenzo** [comment]
Any news?

**Comment by mrkev** [comment]
I gochu 👍

**Comment by pichillilorenzo** [comment]
@mrkev Thanks!

**Comment by mrkev** [comment]
Upon review, we're gonna keep this section focused on setting up an environment to work *with* flow. It's a cool package and it's cool you're using flow, but the purpose of the docs are to help people get started developing with flow, which is tangential (: 

Thanks for sharing though, and keep up the good work!

**Comment by pichillilorenzo** [comment]
@mrkev ok! Thanks for the explanation :+1:

**Pull request closed without merging**
