### PR TITLE
adds Guy Fieri

### PR DESCRIPTION
**Pull request by boneskull**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by boneskull** [comment]
I tried to put him in `hack/` but `.gitignore` disallowed it

**Comment by nmote** [comment]
why

**Comment by brentvatne** [comment]
lgtm :shipit:

**Comment by thejameskyle** [comment]
Goddamnit what have we started...

cc @jdan

**Comment by boneskull** [comment]
😉

**Pull request closed without merging**
