### PR TITLE
Add spread for strings and Iterables

### PR DESCRIPTION
**Pull request by marudor**
fixes https://github.com/facebook/flow/issues/1667
Also added a test for this case.

### CODE REVIEW

**Comment by mroch** [comment]
i suspect that this doesn't work when there's a tvar involved, since `arr` won't be a `StrT` yet. you can probably add a `(StrT _, ArrT _)` rule in `Flow_js.__flow` instead.
t
can you also add negative tests (that produces an error)? for example:

```
var z2: Array<'1' | '2' | '3'> = [...'123']; // error, flow doesn't actually break up the chars
var z3: Array<'123'> = [...'123']; // error, flow does know that the chars are spread
```

I don't think the `z3` case errors right now. you'd fix that by flowing `StrT (reason, AnyLiteral)`.

**Comment by marudor** [comment]
@morch Thanks for the feedback.
I've adjusted it to have a StrT, ArrT case in flow_js.ml.
In the statement.ml I degrade the specific string to a unspecific string (AnyLiteral) and use that to decide if I can spread it or not. (Flow can only spread generic strings now, no String with a specific literal)
Otherwise the function declarations with spread signature will fail.
But it should be okay now.

If you've got something to add please tell me.

**Comment by samwgoldman** [comment]
Ideally we could generalize this to any iterable, not just arrays/strings. I know there's an open issue for that, but I'm on mobile...

**Comment by marudor** [comment]
@samwgoldman I've just did that.
New tests are in iterable_spread.
Everything that has @@iterable will be able to use spread.
Side effect is that the error message for wrong generator usage changed slightly. (See core_tests.exp changes)

**Comment by samwgoldman** [comment]
Wow, nice job digging into this stuff and making progress here! I know it's not a simple code base to get oriented in :)

I think this logic is not quite correct as written, though. Adding a case in `Flow_js.flow` for `(InstanceT _, UseT ArrT _) when is_iterable l` means that the following code would also be allowed:

```js
var x: T[] = iterableOfT
```

The above isn't legal, so we need something a bit more than a subtyping rule.

**Comment by marudor** [comment]
@samwgoldman 
Added a test for your case and fixed it.
Can you think of any other case that would be allowed now although it shouldn't?

If so - would checking the reason of OpenT be reasonable? (OpenT reason has spread operand)

**Comment by gabelevi** [comment]
So if you'd like to make this work for any `Iterable`, you should probably be able to follow the [example set by `for(x of myIterable) { ... }`](https://github.com/facebook/flow/blob/0697ff6610884c4814f579865a5776e2da7419ea/src/typing/statement.ml#L1616).

It would look something like

```OCaml
 and array_element_spread cx type_params_map (loc, e) =
  let spread_element = expression cx type_params_map (loc, e) in
  let reason = mk_reason "spread operand" loc in
  Flow.mk_tvar_where cx reason (fun tvar ->
    let iterable = Flow.get_builtin_typeapp
      cx
      reason
      "$Iterable"
      [tvar; AnyT.at loc; AnyT.at loc] in
    Flow.flow_t cx (spread_element, iterable);
  )
```

* Disclaimer: I haven't tried this and I'm not 100% sure it will actually work. Just an idea :)

**Comment by yinquanteo** [comment]
Ran into this issue when trying to spread an Array Iterator. Is this commit good to merge or are we planning to make this work for any Iterable before merging?

**Comment by samwgoldman** [comment]
@facebook-github-bot import

GitHub won't let me see all the changes here, so importing for review. If memory serves, I don't believe this is quite ready to merge but I'll take a look today.

**Comment by marudor** [comment]
Correct, still not ready.

**Comment by gabelevi** [comment]
@marudor - I'm doing some late-fall spring cleaning of our pull request queue. I'm going to close this PR out for now, but please feel free to re-open if you decide to pick this back up!

**Comment by jessebeach** [comment]
Still running into this in 0.38.0.

**Comment by jessebeach** [comment]
Working as of 0.40.0. Thanks!

**Comment by galkowskit** [comment]
`[flow] [flow] Set (This type is incompatible with spread operand See also: constructor call)`

On:

```
map1.set(string1, {
      ...object1,
      array1: [...set1]
})
```
Where `map1` is a `Map()`, etc.

On 0.40.0.

**Pull request closed without merging**
