### PR TITLE
Fix typo in installation instructions

### PR DESCRIPTION
**Pull request by mgmarlow**
Installation instructions for babel + NPM instructed installing the incorrect babel plugin.

### CODE REVIEW

**Comment by goodmind** [comment]
@mgmarlow I thought there already was ton of PRs fixing this, but each next PR finds old babel plugin... Can you sign CLA?

**Comment by mroch** [comment]
thanks!

@goodmind: there are at least 3 other PRs doing various conflicting things, in various needs of rebasing.

#6396 makes a similar change to a different part of the docs, which seems to have already been fixed
#6952 is similar to this PR, but it also updates `babel-cli` to `@babel/cli` and replaces some other references, which I think mostly have already been fixed by other PRs.
#7049 also switches to `@babel/cli` but additionally installs `@babel/core`. I have no idea if this is necessary.

since this one is current, it seems like the only one that can be merged without conflicts. I think we should probably update to `@babel/cli` and maybe add `@babel/core`. since we don't use this workflow internally, maybe you guys can help test that?

**Comment by mgmarlow** [comment]
@mroch sure I'll take a look. I set my project up using rollup so I didn't need the CLI but I can run through a similar flow with those tools.

**Comment by mgmarlow** [comment]
@mroch You're 100% correct, you also need `@babel/core` when running `@babel/cli`. I've updated the docs accordingly.

**Comment by mroch** [comment]
awesome, thank you! (and also @KidkArolis and @jeffvandyke for #7049)

**Pull request closed without merging**
