### PR TITLE
Add missing type information to HTMLInputElement

### PR DESCRIPTION
**Pull request by SanderSpies**

### CODE REVIEW

**Comment by Emile-Filteau** [comment]
+1

**Comment by xuorig** [comment]
awesome thanks @SanderSpies, hope to see this merged!

**Comment by mroch** [comment]
looks good, just need to re-record the dom test:

```
./runtests.sh bin/flow dom # will fail
cp tests/dom/dom.out tests/dom/dom.exp
./runtests.sh bin/flow dom # should pass now
```

**Comment by SanderSpies** [comment]
Closed due to #1786

**Pull request closed without merging**
