### PR TITLE
Remove void from React$Node type declaration to prevent React.render(undefined)

### LINKED ISSUE #6818: React render() cannot return undefined: React$Node shouldn't be undefined
Hello! 

Small problem we stumbled upon while developing: In React, the `render()` method of a `React.Component` does not accept undefined. 

However, in Flow, the `render()` method returns a `React$Node`, which can be `void` (=`undefined` ? I'm not sure of that).

#### Minimal Working Example:

```jsx
const UndefinedComponent = () => undefined;
```
When you render it:

image

But as you can see on [this Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50qYKBnPmADCDPADsyYwuTEATMvgCqcslAwTZYMgA9Ck2YPLVCAEhG44EqQB4QAPjABvMKxX4wAXjAAKAJSeHAFcVNQ0wAF8gA), Flow doesn't pick it up.

The simplest solution is to remove `  | void ` from the `React$Node` type declaration. (`lib/react.js`, l.13)
May I open a PR to fix that, or is there another way to do it to prevent side effects?

Thanks :smiley: 

---

Environment:

| lib | version | 
| ------------------------------ | ------------------- | 
| Flow                    | 0.79.1         | 
| React                    | 16.3.2         |

### PR DESCRIPTION
**Pull request by Ojisama**
Fix #6818 

> Small problem we stumbled upon while developing: In React, the render() method of a React.Component does not accept undefined.
> However, in Flow, the render() method returns a React$Node, which can be void

```jsx
// Example 1

const Foo = (props: {}) => {} 
<Foo /> // Error from React: Nothing was returned from render.

// Example 2

class Bar extends React.Component<{ foo: string }> {
  render = () => this.props.foo;
}
<Bar /> // Error from React: Nothing was returned from render.
```
---

I split `React$Node`, into:
```jsx
declare type React$RenderableNode =
  | null
  | boolean
  | number
  | string
  | React$Element<any>
  | React$Portal
  | Iterable<React$Node>;


declare type React$Node =
  | void
  | React$RenderableNode
```

And I replace `React$Node` by `React$RendableNode` in the return type of `render()` and `React$StatelessFunctionalComponent`

**Why not simply removing `void` from `React$Node` type declaration?** Because
```jsx
// Example 1

const Parent = (props) => <div>{props.children}</div>

<Parent/> // No error from React
<Parent>{undefined}</Parent> // No error from React
<Parent>{[undefined, undefined]}</Parent> // No error from React

// Example 2

const IterableComponent = (props: {}) => ['foo', undefined, 'bar'];
<IterableComponent /> // No error from React

```

### CODE REVIEW

**Comment by Ojisama** [comment]
I don't know why CI fails upon spawning flow :confused:

**Comment by mrkev** [comment]
Not sure about the CI, but I'll have a look. Thanks for the PR!

For reference to anyone seeing this PR, React complains on a `void` return from `render()`.

> Invariant Violation
Photo(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

**Comment by pakoito** [comment]
Hi @Ojisama. Thanks for the PR! I'd like to keep the `render` methods in files like `tests/react_modules/createclass-callsite.js` still annotated with a type. Would it be possible to address it in the PR before we proceed to merging?

**Comment by Ojisama** [comment]
@pakoito Sure I'll do that! But in this case, shouldn't we also expose the `RenderableType` introduced in this PR (or something equivalent) so people can type their own `render` methods?

**Comment by mrkev** [comment]
@Ojisama what if we change every instance of `React$Node` for `?React$Node` except for `render()` (which we keep as `render(): React$Node;`, and then remove `void` from the definition of `React$Node`.

`React$Node` already includes null so everything should be equivalent (`?T` === `T | null | void`) except for `render()`. Thoughts?

**Comment by pakoito** [comment]
If @mrkev proposal works and we keep the methods annotated, I'm happy :)

**Comment by Ojisama** [comment]
@mrkev @pakoito sounds good, I'll try that and I'll update my PR today :)

**Comment by Ojisama** [comment]
@pakoito `render()` types are back in
@mrkev your solution works like a charm, and is neat :+1:

**Comment by pakoito** [comment]
Thank you both!!

**Comment by mrkev** [comment]
@pakoito hope to see you around in a couple more (:

**Pull request closed without merging**
