### PR TITLE
Only print json if the --json flag is used with the coverage command

### LINKED ISSUE #2315: flow coverage with --json and --color outputs text and json
The flow coverage tool outputs both the colored source text as plain text and then the coverage metrics as json when the two flags are used in conjunction. It's odd so I decided to file an issue.

### PR DESCRIPTION
**Pull request by aackerman**
Fixes #2315

### CODE REVIEW

**Comment by mroch** [comment]
should it error if you use both `--color --json`?

**Comment by aackerman** [comment]
@mroch that's probably clearer behavior. I'll go ahead and change that when I have the chance.

**Comment by aackerman** [comment]
Probably not idiomatic OCaml, but I made changes to print out error information if the user attempts to use the `color` or `debug` flag in conjunction with the `json` flag.

**Comment by avikchaudhuri** [comment]
@facebook-github-bot import

**Comment by samwgoldman** [comment]
It looks like this changes the behavior of `--debug --color` to only output the debug information. Is it intentional that these options should be mutually exclusive? They weren't before and I don't think they need to be, as long as they are exclusive of `--json`.

**Comment by aackerman** [comment]
@samwgoldman I went ahead and fixed that, I don't want to change the existing behavior aside from erroring when flags cannot be used in combination.

**Pull request closed without merging**
