### PR TITLE
Fix typo in modules.doc.js

### PR DESCRIPTION
**Pull request by omerzach**
s/substitue/substitute

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mroch** [comment]
sorry, can't merge this without the CLA being signed

**Comment by omerzach** [comment]
Ah sorry, didn't see the automated response. Just signed it.

**Comment by mroch** [comment]
damn it, GitHub notifications! I have the same problem :)

I fixed this in https://github.com/facebook/flow/commit/62d06b1867328c8cd2c9a306615ce94ec75d98c1, but you're good to go for next time.

thanks for the find!

**Pull request closed without merging**
