### PR TITLE
Add type definition for HTTP methods

### PR DESCRIPTION
**Pull request by NameFILIP**
For the issue https://github.com/facebook/flow/issues/5314

### CODE REVIEW

**Comment by nmote** [comment]
If you are still interested in getting this change in, could you link API docs supporting this change?

**Comment by nmote** [comment]
Closing due to no response. Feel free to reopen if you would still like to pursue this.

**Comment by NameFILIP** [comment]
Hi @nmote, by API docs do you mean something like https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods ?

**Comment by nmote** [comment]
Something like that, but that looks to be the HTTP spec. I'm looking for something that documents the JS functions you've modified. In this case, I would expect those API docs to say that only a valid HTTP methods could be passed as the `method` argument.

**Comment by goodmind** [comment]
https://fetch.spec.whatwg.org/#concept-method

**Pull request closed without merging**
