### PR TITLE
Synchronize stream.Duplex and stream.Writable definition of the end() method

### PR DESCRIPTION
**Pull request by philikon**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by samwgoldman** [comment]
Thanks!

@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
I cannot do that @samwgoldman, because @philikon does not have an active CLA on file.

**Comment by samwgoldman** [comment]
Oh, right. Ping me when you've jumped through the requisite hoops. Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by philikon** [comment]
@samwgoldman all good now

**Comment by philikon** [comment]
Ping?

**Pull request closed without merging**
