### PR TITLE
Covariant length on ReadOnlyArray<.>

### PR DESCRIPTION
**Pull request by popham**
$ReadOnlyArray shouldn't allow `length` setting because it can mutate the array.

### CODE REVIEW

**Comment by vkurchatkin** [comment]
I personally would prefer to have `length` covariant even on mutable arrays

**Comment by popham** [comment]
@vkurchatkin Sure, although I recall reading something about Flow striving toward "JavaScript as it is." Constraining `length` on `Array` seems more in line with "JavaScript as it ought to be." I personally agree with you because I prefer false negatives to false positives (https://github.com/facebook/flow/issues/4246#issuecomment-311188651 was another instance of "JavaScript as it ought to be" in tension with "JavaScript as it is").

Can I get a "shall" directive from the Flow hive at FB? I was too lazy to look it up on the spec, but I noticed that the Node interpreter admits `length` assignments on strings by ignoring them:

```js
const a = "asdf"; //a.length===4
a.length = 1; //a.length===4
a.length = 7; //a.length===4
```

If `length` assignment on `Array` is forbidden, then it seems reasonable that it should be forbidden on `String` also.

**Comment by vkurchatkin** [comment]
`length` mutation on arrays is definetely observable and might even be considered useful. On strings it should do nothing, so that is a no-brainier

**Comment by popham** [comment]
Agreed. The PR is good as-is.

**Comment by nmote** [comment]
Looks reasonable to me. I'd like to see some tests to ensure that (a) `length` mutations are in fact banned on `$ReadOnlyArray`s, and that (b) `length` mutations are still allowed on `Array`s.

**Comment by popham** [comment]
Sure. This closes #4265 BTW.

**Pull request closed without merging**
