### PR TITLE
Added missing attributes and methods for HTMLInputElement

### PR DESCRIPTION
**Pull request by Emile-Filteau**
ref : https://github.com/facebook/flow/pull/1767
I'd really like to see those changes and the other contributor is not replying on the PR.

@mroch

### CODE REVIEW

**Comment by mroch** [comment]
@facebook-github-bot import

**Comment by Emile-Filteau** [comment]
rebased on upstream master

**Comment by Emile-Filteau** [comment]
ping @mroch 
I'm wondering if this is going to make it into master ?

**Comment by mroch** [comment]
sorry for the delay! getting this rebased and landed now.

**Pull request closed without merging**
