### PR TITLE
Add KD functions' lib definition

### PR DESCRIPTION
**Pull request by hczhcz**
Node.js docs:
https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback
https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback

### CODE REVIEW

**Comment by jbrown215** [comment]
Would you mind adding any relevant documentation to the description in your PR? We can review it faster if we don't need to google for the functions.

**Comment by hczhcz** [comment]
Edited.

**Comment by goodmind** [comment]
Why you deleted it?

**Comment by hczhcz** [comment]
@goodmind 

> @jbrown215 has imported this pull request. If you are a Facebook employee, you can view this diff on Phabricator.

From this message, I thought this PR has been merged.

Seems like it is not the case... :|

**Comment by goodmind** [comment]
Merged PRs have `Merged` label and closed automatically
https://github.com/facebook/flow/pull/8032 like this one

**Comment by goodmind** [comment]
@jbrown215 can you merge this?

**Pull request closed without merging**
