### PR TITLE
changing vars to ES6 const (and let)

### PR DESCRIPTION
**Pull request by runn1ng**
I don't *actually* expect this pull request to be merged as-is... however, I made it as an idea/discussion starter/...?

Flow now can do ES6 const/let, and it would be nice to "teach" users to use them in real code, since they are really useful.

So I just changed all `vars` to `const`, where possible, and where not possible, to `let`s.

### CODE REVIEW

**Comment by runn1ng** [comment]
I did *not* test if all those examples are actually working with const, since again, I assumed this will not be accepted anyway. But I can test it of course.

**Comment by samwgoldman** [comment]
Hey, so if you do the legwork and test these examples, I'm prepared to merge.

If you could whip up a script that parses out the code examples and runs them through flow, you will earn my eternal gratitude and I will merge this.

Otherwise, I think this should be closed.

**Comment by runn1ng** [comment]
I could, but I am not sure what should be the result. Since some of the examples are *supposed* to fail, while some are *supposed* to succeed.

But it will be useful anyway so I will try

**Comment by samwgoldman** [comment]
@runn1ng So we're actually migrating our docs to a cool new system. The new docs use a `.doc.js` extension, run through Flow for errors, and are translated to markdown with error messages inline. The new docs are also in the master branch, so we can more easily commit features and docs together.

Unfortunately, that means this PR is targeting an outdated set of docs. Once we've finished the migration, I'm definitely open to this kind of PR.

Thanks a lot for your contribution. Sorry we weren't able to land this one.

**Comment by runn1ng** [comment]
No problem, the system you describe sounds great :)

**Pull request closed without merging**
