### PR TITLE
Add destroy method to streams

### LINKED ISSUE #3204: child_process streams missing destroy property
```
> c = chp.spawn('python', ['-v']);
> c.stdout.destroy()
undefined
```

Right now `child_process$ChildProcess`'s `stdout` and `stderr` are declared as `stream$Readable`. Each of these, including `stdin` have some additional properties beyond `stream$Readable/Writable` including `destroy`.

### PR DESCRIPTION
**Pull request by hiikezoe**
Fixes #3204.

### CODE REVIEW

**Comment by mrkev** [comment]
Could you link to the spec backing up this change?

**Comment by hiikezoe** [comment]
@mrkev, thanks for the reply.  I am afraid I don't quite follow what the spec means and what the backing up mean.

**Comment by hiikezoe** [comment]
Oh thanks.  This change is for node APIs,  so it might be sufficient to put the links to the API references?

https://nodejs.org/api/stream.html#stream_writable_destroy_error
https://nodejs.org/api/stream.html#stream_readable_destroy_error
https://nodejs.org/api/stream.html#stream_transform_destroy_error
https://nodejs.org/api/net.html#net_socket_destroy_exception

**Comment by mrkev** [comment]
Hey @hiikezoe 

I don't see a return value for destroy on https://nodejs.org/api/stream.html#stream_transform_destroy_error, but there's one on the diff. Is this an omission in the docs or does it have to be changed in the diff?

I do see one on https://nodejs.org/api/stream.html#stream_readable_destroy_error but the definition you added returns void.

**Comment by nmote** [comment]
@hiikezoe, if you are still interested in getting this in, I'll work with you to make sure it gets landed promptly.

One useful thing here is the `this` type. You can use that instead of spelling out the type explicitly, e.g. `stream$Readable`.

Could you fix up the return types? I can update the tests when I import, so feel free to just remove the changes to the `.exp` file.

**Comment by hiikezoe** [comment]
hey @nmote, would you mind fixing up them on behalf of me?  I am afraid I don't have the environment for that at this moment.
Thank you!

**Comment by nmote** [comment]
Sure, this is pretty close so I'll just import and then make a few tweaks.

**Comment by nmote** [comment]
I ended up just adding the right `destroy` method declarations to `stream$Writable` and `stream$Readable` and removing them from children of those classes, including the other classes changed in this PR. Once I get a second pair of eyes on this it should land, assuming we don't discover a problem.

**Pull request closed without merging**
