### PR TITLE
Update EventTarget definition to extend HTMLElement

### PR DESCRIPTION
**Pull request by RajaBellebon**
```js
document.body.addEventListener('click', event => {
  console.log(event.target instanceof HTMLElement); // true
});
```

> Note: Hi this is @thejameskyle

### CODE REVIEW

**Comment by thejameskyle** [comment]
What a great PR, this guy makes the best PRs, I can tell you that.

**Comment by jcready** [comment]
I don't believe this is valid since the target could be an SVGElement.

**Comment by asolove** [comment]
Not just SVG, this could be a ton of things. In Node, that includes lots of objects that can be `EventTarget`s, like `FileReader`.

**Comment by TrySound** [comment]
Maybe better to use polymorphic type like `SyntheticEvent`? It will be more consistent then.

**Comment by samwgoldman** [comment]
As noted, this isn't correct. And it's also not correct to make Event polymorphic on the target type, due to bubbling.

**Comment by thejameskyle** [comment]
Last we talked about this, `currentTarget` could be made polymorphic though, right?

**Pull request closed without merging**
