### PR TITLE
Allow selecting Vim key bindings on /try/

### PR DESCRIPTION
**Pull request by jez**
I'm a huge fan of Vim, and CodeMirror has a really nice Vim plugin.
This PR adds a dropdown `<select>` next to the dropdown for versions.
I broke this change up into 2 commits (the first one is actually
unrelated to adding Vim key bindings).

Completely open to suggestions; also if this is a feature you're not
interested in, I'd love to hear why but I'd completely understand.

### Commit Summary

- **Pin js_of_ocaml version** (c690935b)

  Looks like the newest version (>= 3.0) of `js_of_ocaml` changes one of
  the APIs we're using. I had to manually pin this to version 2.8.1 to
  get it to work.

  It looks like we're also manually pinning this version in the Travis
  build (`resources/travis/install_deps.sh`). I'm new to OCaml; is there
  a better way to declare a projects `opam` dependencies than a note in
  the README?

- **Add dropdown to choose Vim keybindings** (aa4ccf98)

  We have to load a few more scripts on the page. In total, this adds 80
  KB when loading the `/try/` page. I didn't spend the time figure out
  how to make this load asynchronously on selecting "Vim" because I
  figured this was all dwarfed by the time it takes to load our 2.8 MB
  flow.js script.

### Notes

Also, the default way to build the website didn't work for me right
away. Instead, I had to run these commands:

    rm -rf website/statics/master/{flow.js,flowlib}
    cp bin/flow.js website/static/master/flow.js
    cp -r lib website/static/master/flowlib
    cd website
    make

Steps to reproduce the error I ran into: I tried to build the site
from a fresh clone of the repo, and followed the commands listed in
`website/README.md`. When running `make` though, I got a Jekyll error:

    jekyll 3.2.1 | Error:  File exists @ syserr_fail2_in - /Users/jake/Dropbox/Documents/Programming/pl/flow/website/_site/static/master/flow.js

I'm not sure if this is something we should look into more broadly
(i.e., in a separate issue) or if it's an error you guys are already
familiar with.

### Screencast

[video](https://www.dropbox.com/s/v8x5l61k9m6wwf6/try-flow-vim-demo.mp4?dl=0)

### CODE REVIEW

**Comment by jez** [comment]
Hm, looks like the failing tests are unrelated to the change I made:

```
[00:14:48] [Γ£ù] FAIL:  ide\lazy  (8/8 tests. 27 steps passed. 7 steps failed)
```

I see that some other open PRs are failing these tests specifically too.
Curious to know whether these tests are known flaky, or whether I should
suspect something wrong with my change.

**Comment by daehli** [comment]
Hi @jez, 

Are you still have the `jekyll 3.2.1 | Error:  File exists @ syserr_fail2_in - /Users/jake/Dropbox/Documents/Programming/pl/flow/website/_site/static/master/flow.js` error ? 

I ran into this error too. If you have a solution can you share it.

Thanks :)

**Comment by jez** [comment]
> If you have a solution can you share it.

I shared my solution directly above that error message:

```
rm -rf website/statics/master/{flow.js,flowlib}
cp bin/flow.js website/static/master/flow.js
cp -r lib website/static/master/flowlib
cd website
make
```

**Comment by goodmind** [comment]
This errors now
```
opam install -y js_of_ocaml.2.8.1
The following dependencies couldn't be met:
  - js_of_ocaml → ocaml < 4.04.0
      base of this switch (use `--unlock-base' to force)

No solution found, exiting
```

**Pull request closed without merging**
