### PR TITLE
Add "destroy()" to stream$Stream

### PR DESCRIPTION
**Pull request by piglovesyou**
I'm getting this error in my project.
`Error:(124, 5) property `destroy`. Property not found in stream$Writable` 
Let me fix it.

https://nodejs.org/api/stream.html#stream_writable_destroy_error

### CODE REVIEW

**Comment by piglovesyou** [comment]
> mixed

Sure, I force pushed to mine. Sorry, I didn't understand the next one.

> It also looks like the object itself (stream$Stream).

**Comment by piglovesyou** [comment]
fixing

**Comment by piglovesyou** [comment]
@mrkev Done. Glad if you check this again.

**Comment by nmote** [comment]
Looks good, I will get this merged

**Comment by nmote** [comment]
Actually, when I took a closer look I realized that the base `stream` class doesn't actually have the `destroy` method. In both the implementation and the docs, `destroy` appears on the individual subclasses of `stream`. I think the Flow libdefs should remain faithful to the implementation, even if it doesn't seem to make a difference right now.

Furthermore, `destroy` returns `this`, not `void`.

There are a few other open PRs that address this issue and seem a bit closer to the ideal solution. Even though they were opened later, I think it will be fastest to close this and work with the other PR authors.

**Pull request closed without merging**
