### PR TITLE
Declare HTMLTableRowElement

### LINKED ISSUE #2170: identifier `HTMLTableRowElement`. Could not resolve name
I have the following code:

```
/* @flow */

export function findTableRowParent(el:HTMLElement):?HTMLTableRowElement {
  while (!(el.parentNode instanceof HTMLTableRowElement)) {
    if (!el.parentNode) {
      return null;
    }
    el = el.parentNode;
  }
  return el.parentNode;
}
```

I get this error:
image

Not sure what is going on here, cuase flow can resolve other dom types like `HTMLTextAreaElement`.

### PR DESCRIPTION
**Pull request by saml**
fixes #2170
Starting declaration of HTMLTableRowElement

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by samwgoldman** [comment]
Changes like this tend to move around line numbers, which changes the expected output. Don't worry though, I'll rerecord the tests internally before pushing out.

Thanks for your contribution!

@facebook-github-bot import

**Comment by samwgoldman** [comment]
Oh, oops! Please sign the CLA first, then I'll push. Thanks again! :)

**Comment by facebook-github-bot-5** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3698407) to review internal test results.

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by saml** [comment]
@samwgoldman Ah, I did not even build and test before submitting PR :)

I updated dom.exp file manually.  How can I regenerate .exp file in case I modify lib/*.js in the future?

And should PRs be squashed to single commit?

Thanks

**Comment by samwgoldman** [comment]
@saml Thanks for updating your PR. I took the liberty of making the same fixes on our end as well, so no worries there. The change still needs to be reviewed internally, but once it's approved and pushed out you will see the change as a single commit here attributed to you as author.

Thanks again for contributing!

**Pull request closed without merging**
