### PR TITLE
Add type property of Selection class to declaration

### PR DESCRIPTION
**Pull request by nunull**
The type definition for the `Selection` class is missing the `type` property. See [https://www.w3.org/TR/selection-api/#attributes](https://www.w3.org/TR/selection-api/#attributes).

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mroch** [comment]
thanks!

can you re-record the `dom` test? adding a line shifted the expected line numbers down.

just run `./runtests.sh bin/flow dom; cp tests/dom/dom.out tests/dom/dom.exp`. the first command runs the test, the second copies the updated output to the expectation file.

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by nunull** [comment]
Sure, here you go.

**Comment by gabelevi** [comment]
Awesome, thanks! Merging...

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3926232).

**Pull request closed without merging**
