### PR TITLE
[Library definitions] Add optional `propTypes` to `React.AbstractComponentStatics`

### LINKED ISSUE #7484: propTypes no longer part of React.AbstractComponentStatics
One cannot reference `propTypes` on a `ComponentType<*>` since 2e7d5a26babe69f2b17cba25f6f62a524534c635.
Is this intended? If yes, do you have a suggestion for handling this?

Example code:
```
import * as React from 'react';

function testHoc<-Props>(Component: React.ComponentType<Props>, props: Props) {
	return class Wrapper extends React.Component<Props> {
      static propTypes = Component.propTypes; // Error here: property `propTypes` is missing in 
`React.AbstractComponentStatics`
      
      render() {
      	return <Component {...props} />
      }
    };
}
```

[Flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqlACuAOwbo4wsAWpkCACTh0APAFoACs2xkAfAAoAwi1zDqwggC4qXAgDpDOCaYIAVAJ7ZqSjXC3aANGDYmmSW3loAlGAA3qgAkJwEgniSdDDkFADqeCTYHnhg1AAe0sIAJhQ09Lb2xk5ewdrRqGAtrbIkBOh0gZpuHhQAvGA1jmY2QT59Mnytrc2zYJxl1Hi6kTELYPHUiclgSiMmZtE2pxNaAL5gwNrzsxd3YBd8F0A)

### PR DESCRIPTION
**Pull request by cprodescu**
* fixes #7484
* add test accessing `Component.propTypes`
* add test assigning `propTypes` to `AbstractReactComponent`
* fix line numbers for other tests due to shift in `lib/react.js`

This is basically https://github.com/facebook/flow/pull/7486 (except I accidentally deleted the branch on origin #classic :( )

cc @jbrown215  @TrySound

### CODE REVIEW

**Comment by jbrown215** [comment]
Lookin' good! Thank you!

**Comment by cprodescu** [comment]
Thank you! Is there any other action I need to take here?

**Comment by jbrown215** [comment]
No, I'll handle the conflicts! Just haven't had time to merge yet.

**Comment by jbrown215** [comment]
This introduces a bunch of new errors in our codebases. I'll have to investigate them before I merge.

**Comment by goodmind** [comment]
@jbrown215 is this still revelant?

**Comment by jbrown215** [comment]
Probably, but I still haven't looked into the new errors.

**Comment by Brianzchen** [comment]
Hi @jbrown215 is this PR still planned to be worked on and merged? I'm working on a library that defines propTypes and flow types and would be really keen to use this.

**Comment by cprodescu** [comment]
Closing in favor of https://github.com/facebook/flow/pull/8476

**Pull request closed without merging**
