### PR TITLE
#jgaj

### PR DESCRIPTION
**Pull request by Jericho25**
#jgaj

### CODE REVIEW

**Comment by jeffmo** [comment]
I think you picked the wrong target branch to merge a gh-pages pull request (seems this is trying to merge into 'master' when it should be merged into 'gh-pages')

**Comment by Jericho25** [comment]
No.That would be fine...As seen above..

**Comment by jeffmo** [comment]
@Jericho25: Hmm, I'm a bit confused... Are you planning on re-targeting this PR at the `gh-pages` branch? Or am I missing what you're aiming for here?

**Comment by bgw** [comment]
According to @brigand,

> this user has been doing this on a number of projects today.

https://github.com/facebook/react/pull/4263#issuecomment-117792728

**Comment by jeffmo** [comment]
Thanks for the pointer @bgw.

@Jericho25: Please let us know if this PR was intentional. I'm going to close it for now assuming that it was not.

**Pull request closed without merging**
