### PR TITLE
Update flow comments in getting starting page

### PR DESCRIPTION
**Pull request by montogeek**
As pointed out by https://flowtype.org/docs/new-project.html#typechecking-your-files all files should use `/* @flow */` comment at the top of the file, this PR updates getting starting guide to use `/* @flow */` comments

### CODE REVIEW

**Comment by samwgoldman** [comment]
As we discussed on IRC, there's really no difference between `/* @flow */` and `// @flow`. In light of that, what is the motivation for this change?

**Comment by montogeek** [comment]
@samwgoldman Oh, is you :)
I know it make not difference, just trying to use the same format everywhere, to be consistent :)

**Comment by samwgoldman** [comment]
OK, sounds good to me. Thanks!

@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1807583936138350/int_phab) to review internal test results.

**Comment by montogeek** [comment]
Thanks to you :)

**Comment by mroch** [comment]
`/* */` is reserved for docs, so you have to use `//` in code sections. this messed up the formatting and I think needs to be reverted. :/

**Comment by montogeek** [comment]
Sorry for the trouble

**Comment by samwgoldman** [comment]
Whoopsies! Thanks for catching, Marshall. I'll do the revert now.

**Pull request closed without merging**
