### PR TITLE
Usage of object spread for exact object types

### PR DESCRIPTION
**Pull request by mattgstevens**
Came across this issue: https://github.com/facebook/flow/issues/2626 and decided it could be in the documentation :)

### CODE REVIEW

**Comment by saadq** [comment]
Instead of

```ts
type FooBarT = {| ...FooT, BarT |}
```

did you mean

```ts
type FooBarT = {| ...FooT, ...BarT |}
```

**Comment by mattgstevens** [comment]
Good catch @saadq updated and expanded the example since the failure wont be at the type definition, but when using it for a variable binding.

**Comment by mattgstevens** [comment]
@fishythefish is there anything else to do for this? think it is ready for a merge. 

mentioning you as it seems you have merged other PRs recently

**Comment by apsavin** [comment]
Related to #5973

**Pull request closed without merging**
