### PR TITLE
Set.prototype.size is a getter, not a data property

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by jeffmo** [comment]
It's true that it's a setter, but we don't have "non-experimental" support for getters/setters right now (since we can't reason about side effects yet).

Is there more context to this change? Does this affect how Flow analyzes uses of a `Set` in some way that's problematic?

**Comment by michaelficarra** [comment]
@jeffmo Yeah, I was trying to add flow to [a recent project of mine](https://github.com/michaelficarra/samevalueset) which subclasses `Set`. I ran into a number of issues, including this one. It would not allow me to create a `size` getter because it was typed as a data property.

Among the other Flow bugs I ran into were [the complete lack of Iterable support](https://github.com/facebook/flow/issues/1059) and some `FunctionBindT` error trying to type

```js
const call = Function.prototype.call.bind(Function.prototype.call);
```

I eventually just gave up on Flow, which is a shame for such a small, modern, idiomatic module.

**Comment by jeffmo** [comment]
Gotcha. Ok, so since getters/setters aren't really supported well in Flow, I think we'd either need to come up with a different solution here or find a way to map getters/setters in libdefs back to normal properties when getter/setter support isn't enabled.

Going to close this out for now, but I've opened an issue [here](https://github.com/facebook/flow/issues/3426) to help us find a solution

**Comment by michaelficarra** [comment]
👍

**Comment by samwgoldman** [comment]
> no __proto__ support in object initialisers

This is on my TODO list, FWIW.

**Comment by michaelficarra** [comment]
Nice! Good to hear.

**Comment by michaelficarra** [comment]
@jeffmo It appears Flow has support for getters/setters now. Can we re-open this PR?

**Pull request closed without merging**
