### PR TITLE
Add oncontextmenu to HTMLElement

### LINKED ISSUE #7357: oncontextmenu is misisng from HTMLButtonElement
I'm seeing this error: 

> Cannot assign onContextMenu to bp.oncontextmenu because property oncontextmenu is missing in HTMLButtonElement [1].

which is surprising to me because `HTMLButtonElement` has other properties like `onblur` and `onclick`

### PR DESCRIPTION
**Pull request by jasonLaster**
Fixes #7357

### CODE REVIEW

**Comment by jasonLaster** [comment]
Out of curiosity, is it documented that the flow [repl] doesn't work with `document`?

[repl]:https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodUCuA7AxgFwEs5swo44AKASjAG9UwxcSBnfMAUxjAF4wAJnFyYAtp2z4AdLgBOnAIb5OAURidxkygCIBhAG7bqjLjCklcMQrgDWfMDT4A+egF8T3c3hLKAHvk1Me0deFzp3VyA

**Comment by jbrown215** [comment]
The flow repl doesn't load all of the libdefs, so it's possible that the one where document is defined is not loaded.

You may need to re-record tests here. I use `./runtests.sh` at the root of the flow repo to do that.

**Comment by nmote** [comment]
Could you link supporting docs?

**Comment by jasonLaster** [comment]
I'm getting tripped up on the getting started guide

I was seeing this

```
➜  flow opam upgrade
[ERROR] No switch is currently set. Please use 'opam switch' to set or install a switch
```

which was fixed by doing


```
opam switch create flow 4.05.0
```

now `make` works, but `make js` does not and `./runtests.sh` fails...

**Comment by jbrown215** [comment]
What's the error message you get with `make js`?

**Comment by jasonLaster** [comment]
https://gist.github.com/be1245924d4302f28118e902e3836589


runtests.sh fails with this

```
      10
      11 Stderr:
      12 ./runtests.sh: line 493: /Users/jlaster/src/_os/flow/: is a directory
      13 flow check return code: 126
      14 [✗] ERRORED: annot2
      15
```

**Comment by nmote** [comment]
@jasonLaster You have to pass the location of the built Flow binary as the argument to `./runtests.sh`... it should fail with a better error message though if you don't.

**Comment by nmote** [comment]
Anyway, I'm willing to take care of re-recording the tests, although it's certainly simpler if you are up for it. The main thing I need here is a link to supporting docs so I can verify that this change is correct.

**Comment by jasonLaster** [comment]
here are some docs
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oncontextmenu

**Comment by jasonLaster** [comment]
@nmote thanks i was able to run `./runtests.sh -r -b bin/flow`. It looks like there are still some failing tests. I'd love a bit of help to see what else i should do...

**Comment by nmote** [comment]
Thanks, I'll take a look

**Comment by nmote** [comment]
I ran the tests and got a much smaller and more reasonable test diff. I'm not sure what went wrong, but I'll get it committed with the updated test output.

**Comment by jasonLaster** [comment]
weird. Anyways, thanks for the help.

As a sidenote, it would be nice to have some improvements to the docs on using `opam switch` and running tests

**Comment by nmote** [comment]
Understood. If you have specific suggestions, feel free to tag me in a PR and I will make sure to take a look.

**Pull request closed without merging**
