### PR TITLE
Adding KeyboardEvents to EventTarget

### PR DESCRIPTION
**Pull request by runn1ng**
Fixing #1298.

This is a solution that *works*, but I somehow feel it's *wrong*. I hope someone does something, that feels cleaner to me :)

I fixed it in a best way I can :)

### CODE REVIEW

**Comment by mroch** [comment]
the dom test is always causing conflicts! I'll rebase while merging it.

This seems pretty reasonable to me. I'm not sure what a cleaner solution would look like.

**Comment by mroch** [comment]
@facebook-github-bot import

**Comment by runn1ng** [comment]
Those "FB employee" posts are always teasing me! :)

OK, thanks. I can fix the tests myself later, but not now (on mobile now)

**Comment by mroch** [comment]
#1247 will cause more merge conflicts if it lands first, so it's not a big deal for me to do it depending on which one goes first.

**Comment by runn1ng** [comment]
I have corrected the tests (and squashed them to one commit).

I have rebased the branch so it's on the last buildable master (as I am writing this, the latest master produces error), so Travis should build it fine :)

**Comment by runn1ng** [comment]
...the tests are not working again :(

**Comment by samwgoldman** [comment]
I was originally apprehensive about this change, because adding more intersection types to the core library definitions can lead to confusing error messages, but that may change soon.

Don't worry about the tests, I'll update them internally during import. Might be a little bit before we can merge this though. Thanks for the contribution!

**Comment by runn1ng** [comment]
I've rebased+updated tests, for what it's worth :)

**Comment by gabelevi** [comment]
Merged this! Thanks for the contribution and apologies that it took so long to merge!

**Comment by runn1ng** [comment]
Hm. For some reason, this still doesn't work in my code.

     form.addEventListener('keypress', (e: KeyboardEvent) => {...})

The whole error:

```
/tmp/flow/flowlib_2fe1bd92/dom.js:62
 62: type EventHandler = (event: Event) => mixed
                                 ^^^^^ Library type error:
 62: type EventHandler = (event: Event) => mixed
                                 ^^^^^ Event. This type is incompatible with
 90:         form.addEventListener('keypress', (e: KeyboardEvent) => {
                                                   ^^^^^^^^^^^^^ KeyboardEvent. See: (my code).js:90
```

How is it possible? :(

**Comment by runn1ng** [comment]
Switching the order of the lines fixes it magically. If I change

```
declare class EventTarget {
    removeEventListener(type: KeyboardEventTypes, listener: KeyboardEventListener, useCapture?: boolean): void;
    addEventListener(type: KeyboardEventTypes, listener: KeyboardEventListener, useCapture?: boolean): void;
    detachEvent?: (type: KeyboardEventTypes, listener: KeyboardEventListener) => void;
    attachEvent?: (type: KeyboardEventTypes, listener: KeyboardEventListener) => void;

    removeEventListener(type: string, listener: EventListener, useCapture?: boolean): void;
    addEventListener(type: string, listener: EventListener, useCapture?: boolean): void;
    detachEvent?: (type: string, listener: EventListener) => void;
    attachEvent?: (type: string, listener: EventListener) => void;
    dispatchEvent(evt: Event): boolean;
}
```

to

```
declare class EventTarget {
    removeEventListener(type: string, listener: EventListener, useCapture?: boolean): void;
    addEventListener(type: string, listener: EventListener, useCapture?: boolean): void;
    detachEvent?: (type: string, listener: EventListener) => void;
    attachEvent?: (type: string, listener: EventListener) => void;
    dispatchEvent(evt: Event): boolean;

    removeEventListener(type: KeyboardEventTypes, listener: KeyboardEventListener, useCapture?: boolean): void;
    addEventListener(type: KeyboardEventTypes, listener: KeyboardEventListener, useCapture?: boolean): void;
    detachEvent?: (type: KeyboardEventTypes, listener: KeyboardEventListener) => void;
    attachEvent?: (type: KeyboardEventTypes, listener: KeyboardEventListener) => void;
}
```

it starts working. But it doesn't seem "correct".

**Pull request closed without merging**
