### PR TITLE
readme.md should be more focused on installing & usage.

### PR DESCRIPTION
**Pull request by Foxhoundn**
I've decided to finally add Flow to our dev stack on the project I am currently working on. I had a bit of trouble getting started though, as I was a bit surprised that the first thing I saw in the readme is how to build Flow instead of how to actually install it and get up & running.

For me personally it was quiet stressful as I wasn't sure if I need to do the building or I can just install using brew (I'm pretty sure there's a diagnose for that).

I am not very good at writing stuff so just take this as a poke & point to the better (didn't want to use "right") direction.

Thanks,

Foxhoundn

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by gabelevi** [comment]
This seems like a good idea! Thanks for the contribution!

**Comment by gabelevi** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1240142599359481/int_phab) to review.

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Pull request closed without merging**
