### PR TITLE
Adding extra URL properties

### PR DESCRIPTION
**Pull request by fabiomcosta**
Adding extra URL properties  according to https://developer.mozilla.org/en-US/docs/Web/API/URL

I also check on Chrome and everything matches.
tests were added to the tests/dom/URL.js file

### CODE REVIEW

**Comment by samwgoldman** [comment]
What's up with the flow-state.gif change?

**Comment by fabiomcosta** [comment]
@samwgoldman I have no idea, it kept showing up, I thought there was some kind of script that updated it after a test run.
I'll remove it from the PR.

**Comment by fabiomcosta** [comment]
updated

**Comment by samwgoldman** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1254071451284793/int_phab) to review.

**Pull request closed without merging**
