### PR TITLE
Fixes String#match and RegExp#exec declarations. (#2450)

### PR DESCRIPTION
**Pull request by michelle**
The current declaration of String#match fails when trying to access the `index` and `input` properties of the return value.

Tests are failing because error messages are different due to new line numbers. I didn't want to update these by hand and I'm not sure how to update them otherwise (played around with `generate_exp.sh`).

### CODE REVIEW

**Comment by michelle** [comment]
Hmm, it seems possible that intersection types don't play nicely with Arrays and Objects. After running tests, the only non-line-number-change diff is: 

```diff
-overload.js:7
-  7: var x1: number = "".match(0)[0];
-                      ^^^^^^^^^^^^^^ string. This type is incompatible with
-  7: var x1: number = "".match(0)[0];
-             ^^^^^^ number
-

-overload.js:8
-  8: var x2: number = "".match(/pattern/)[0];
-                      ^^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
-  8: var x2: number = "".match(/pattern/)[0];
-             ^^^^^^ number
-

-Found 12 errors
+Found 10 errors
```

**Comment by avikchaudhuri** [comment]
I don't think this will work, see: https://flow.org/try/#0CYUwxgNghgTiAEA3W8AeAueBBGMoE8AeAZwBcYBLAOwHMA+eAMngG8AfeEVcqTMy2vDYBfANwAocQApUAOi49MVAK4BbAEYgYASlFA

Not sure if this is a bug that should be fixed separately in Flow, but this diff can't be merged in as is.

**Comment by KevinGrandon** [comment]
> I don't think this will work, see: https://flow.org/try/#0CYUwxgNghgTiAEA3W8AeAueBBGMoE8AeAZwBcYBLAOwHMA+eAMngG8AfeEVcqTMy2vDYBfANwAocQApUAOi49MVAK4BbAEYgYASlFA
> 
> Not sure if this is a bug that should be fixed separately in Flow, but this diff can't be merged in as is.

@ avikchaudhuri I just went back and tried that try flow link, and it seems to be erroring as expected now. Perhaps something was fixed in flow in the last 1+ year that now allows this to work? Can we revisit this if possible now?

**Comment by KevinGrandon** [comment]
Looks like the landscape has changed a bit. Using this as inspiration along with the new code in master I've opened: https://github.com/facebook/flow/pull/6790

**Pull request closed without merging**
