### PR TITLE
Member expression refinement

### LINKED ISSUE #2990: Treat bracket property access with string literals the same as dot property access
I use objects with properties that are not valid identifiers in several places in my code. When I use bracket property accessors, I don't seem to be able to type-check the same way as I can with valid javascript property names. Here is an example with unions using both exact object types and tagged unions.

```js
/* @flow */
type exactObjectType = {|
  'a.b': {};
|} | {|
  'a.c': string;
|};

type disjoint = {
  'tag.tag': 'first';
  'a.b': {};
} | {
  'tag.tag': 'second';
  'a.c': string;
};

const testDisjoint = (param: disjoint): string => {
  if (param['tag.tag'] === 'second') {
    return param['a.c'];
  }
  return '';
}

const testFunction = (param: exactObjectType): string => {
  if (param['a.c'] != null) {
    return param['a.c'];
  }

  return '';
};
```

The above examples work if I replace all invalid identifiers with valid ones and instead use dot property access. Are there plans to treat bracket property accesors with string literals the same as dot notation?

### LINKED ISSUE #7475: Refinements fail for bracket notation
Seems related to #1399

Flow version: 0.92.1

## Expected behavior
Refinements between bracket and dot notation are functionally equivalent.

## Actual behavior
Flow doesn't properly refine types when checking for the existence of properties using bracket notation.

Try-Flow Link:
https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUASAOQwLQHsA7AGxCwC4oBnYAJwEtCBzAGijRQF8BuNNUSFABCCZCnbYhBEmUo0GzFhx58AxkRpQAZvnyU4iJDmmkKULACMAhrSwq0ACi0BXQquD0i1YM61aHwAAWjEz6UOJCAJSUAG749AAmyGhQUPRaUAHBzADaxkSmALqRKcmpUAD0FVAJ+N6+GTq0sOypnKUQxFTQSKWV1bX1ftr4zSKl7ZxOupGRvHwC0DAATKKomDAA+gUgcnQhbMrzi8KrhuKYQtsyewqsR2oawCP4y-pnyFs7lJY2dvNOVzuTyEIb+IIhd7hU7RKBxRJlNIZLIhAB0XxkJVSvXKVRqdRoDRGzTgEw6XR6fTxg0JwyawlaUEm01es14qVKpSAA

### PR DESCRIPTION
**Pull request by goodmind**
Follow-up to #7597 

Fixes #7475 again
Fixes #2990 again

### CODE REVIEW

**Comment by goodmind** [comment]
I'm probably missing bunch of refinements with `TestPropT`

**Comment by goodmind** [comment]
Hmm, this breaks one of tests

**Comment by gkz** [comment]
Closing this as the examples in the two linked issues now work.

**Pull request closed without merging**
