### PR TITLE
Mark defaultProps as covariant in React libs

### LINKED ISSUE #3008: Flow doesn't support getters for defaultProps in es6 classes
Given an example es6 style react class like:
```
/* @flow */

import React, { Component } from 'react';

type DefaultProps = {
    foo: number
}

class OnlyGetter extends React.Component {
    static get defaultProps(): DefaultProps {
        return {
            foo: 3
        }
    }
}
```

and `unsafe.enable_getters_and_setters=true` is specified under the `[options]` header of the `.flowconfig`

Flow incorrectly finds the following error, despite it being valid to react (in that react correctly makes use of the `defaultProps`):
```
test.js:5
  5: class ClassGetterTest extends Component {
           ^^^^^^^^^^^^^^^ ClassGetterTest. Covariant property `defaultProps` incompatible with invariant use in
  5: class ClassGetterTest extends Component {
                                   ^^^^^^^^^ statics of React$Component


Found 1 error
```

As far as I know, this is the only way to set `defaultProps` at runtime rather than load time.

From what I can tell, this is due to the fact that the flow type definition expecting `defaultProps` to be able to be set as well as gotten, even though afaik react really only ever gets the value (I could be wrong here?).

Adding a dummy setter seems to work around the problem and causes flow to succeed:
```
    static set defaultProps(props: DefaultProps) {
        // do nothing
    }
```

Unfortunately, it doesn't seem possible to solve this problem in the react definition by marking `defaultProps` as covariant (ie. `+defaultProps`) because this breaks valid situations like:
```
class LaterDefaultProps extends React.Component {
    static defaultProps: DefaultProps
}

LaterDefaultProps.defaultProps = {
    foo: 3
}
```

I can't find a way to express "invariant or covariant, but never contravariant" in the flow definition, but this may be able to be resolved if #1189 is by providing a union between a definition where `defaultProps` is invariant and a definition where `defaultProps` is covariant.

[There's a test case here](https://github.com/Novex/flow/tree/7226046335c5645e2da639b9054c5590ac94872c/tests/react_defaultProps) - making it pass should resolve this problem.

### PR DESCRIPTION
**Pull request by Novex**
This is so we don't have to include a dummy setter to satisfy Flow when using a getter to dynamically construct defaultProps

This resolves #3008, avoiding the `Covariant property `defaultProps` incompatible with invariant use in statics of React$Component` error and adds a test to ensure that future getters for defaultProps will typecheck properly.

### CODE REVIEW

**Comment by vkurchatkin** [comment]
The problem with this is that it's gonna break something like this:

```js
MyComponent.defaultProps = {};
```

**Comment by Novex** [comment]
I *knew* I was missing an edge case!

I can't seem to find a way to mark a field as "covariant or invariant, but not contravariant" (ie. accepts anything but not only inputs).

Anyone wiser than me have any ideas here? Otherwise I'll close this and go back to the drawing board on #3008.

**Comment by vkurchatkin** [comment]
Well, object with covariant property is a subtype of object with invariant property:

```js
declare function test(x: { +foo: string }): void;
declare var x: { foo: string };
test(x);
```

So, you can do this:

```js
class X {
 static +x: string;
}

class A extends X {
  static x: string;
}

A.x = '';
```

But it requires you redeclare inherited property as invariant every time.

**Comment by Novex** [comment]
Thanks for the explanation - I think I understand what you're saying.

Unfortunately, the requirement to redeclare the inherited property as invariant when you want to set it after class definition is pretty much equivalent to the workaround of creating a dummy setter when you want to use a getter :(

I did stumble upon #1189, which if resolved would let us do something like define `React$Component` as a union type between a class with `defaultProps` as covariant and another class with `defaultProps` as invariant. But other than that I'm still stumped.

**Comment by Novex** [comment]
I can't currently see a way to express this in the flow definition without breaking something, so I'm going to close this and come back to it (hopefully) in the future.

**Pull request closed without merging**
