### PR TITLE
Add Function.prototype.toString

### PR DESCRIPTION
**Pull request by disnet**
`toString` was missing from `Function.prototype`. This adds it.

### CODE REVIEW

**Comment by mroch** [comment]
I think this is inherited from `Object.prototype`. was something complaining that it was missing?

**Comment by disnet** [comment]
@mroch minimal test case:

```js
function F() {}
if (Function.prototype.toString !== F) {

}
```

errors with

```
3: if (Function.prototype.toString === F) {
                          ^ property `toString`. Property not found in
3: if (Function.prototype.toString === F) {
       ^ Function
```

**Comment by mroch** [comment]
Hmm, this errors:

```
(Function.prototype.toString: empty);
```

([Try Flow](https://flowtype.org/try/#0BQMQrgdgxgLglgewgOgA4CcEywT1QU2WwGUZ04IBzALgAJ8BbVGHASgG4AoIA))

so I think in some cases we do know it's inherited. Something must be wrong with using inherited properties in a conditional, which goes through a slightly different codepath.

**Comment by thejameskyle** [comment]
@mroch also pointed out that this no longer errors in master. Gonna close this.

**Comment by mroch** [comment]
https://github.com/facebook/flow/commit/4b887d7972e5a7c597f4c337e8540fac6661eaed fixed this unintentionally.

Turns out that it was correctly falling back to looking at `Object.prototype`, but erroring because the `ObjProtoT ~> HasPropT` rule always said the prop was not found instead of allowing Object.prototype properties.

**Pull request closed without merging**
