### PR TITLE
Add missing esproposal.nullish_coalescing warning

### PR DESCRIPTION
**Pull request by goodmind**
Add missing warning

### CODE REVIEW

**Comment by mroch** [comment]
was this not being caught by the parser here? 
https://github.com/facebook/flow/blob/c48b92cbaa7225d5843f162b763e0517b415552f/src/parser/expression_parser.ml#L315-L316

i wonder why optional chaining is erroring in statement.ml instead of the parser.

**Comment by goodmind** [comment]
@mroch there's comments about it, it is for nicer error messages, also parser options is always enabled

**Comment by mroch** [comment]
you mean nicer because one has `code` formatting and the other doesn't?

it parses the same way with the option enabled or not, so if we made the errors prettier and disabled the parser option along with the typechecker option, then would it behave the way you want?

I don't love the duplication this adds, but unifying them could be future work.

**Comment by goodmind** [comment]
@mroch Yeah, it is probably because of code formatting

**Comment by goodmind** [comment]
@mroch could be it is also related to how location of error is determined if it is halted in the middle of parsing?

**Comment by goodmind** [comment]
@mroch so would you merge or maybe I should add some comments that this is temporary before parser errors are unified with type errors?

**Comment by goodmind** [comment]
Looks like this proposal going into stage 3
https://onedrive.live.com/view.aspx?resid=5D3264BDC1CB4F5B!5285&ithint=file%2Cpptx&authkey=!AC0xl44ouDVFxEM

**Comment by goodmind** [comment]
I'm going to close this, since it is stage 3

**Pull request closed without merging**
