### PR TITLE
feat(docs): Update README.md

### PR DESCRIPTION
**Pull request by iamdarshshah**
### Changes
- [x] Added Flow logo (image source: `https://opensource.facebook.com/projects`)
- [x] Aligned header elements to the center

> This will make it look a lot cleaner. It's good to include a logo in the docs, thus added it to the top.

### CODE REVIEW

**Comment by mroch** [comment]
indeed, looks nice. thanks!

**Comment by iamdarshshah** [comment]
Thanks @mroch 👍

**Comment by Brianzchen** [comment]
@iamdarshshah can you update this PR? It has a conflict since #8454 got merged recently

**Comment by iamdarshshah** [comment]
@Brianzchen Thanks for a quick reminder. PR is now Updated 👍

**Comment by Brianzchen** [comment]
@iamdarshshah the image you've used doesn't seem very stable, looks like the url expires over time?

**Comment by gkz** [comment]
Close in favor of other PR

**Pull request closed without merging**
