### PR TITLE
Allow checking of .es6 files

### PR DESCRIPTION
**Pull request by Eyyub**
This pull request allows checking of .es6 files with `flow {start|single|server} --check-es6-files`.
See #499

### CODE REVIEW

**Comment by aikeru** [comment]
Is ".es6" an extension we want to stick with? ES7 is going to come a lot quicker than ES6 did.
Isn't there already an option to target arbitrary file names/paths with flow?

**Comment by Eyyub** [comment]
Maybe, not to my knowledge.
Adding an option to target arbitrary file extension is easy, it's more a design issue than anything else.

**Comment by jeffmo** [comment]
Thanks for sending this over!

Rather than trying to predict all the possible extensions, it would be better if we created a .flowconfig option that allows one to specify a custom extension to expect (where the default is the existing `[".js";".jsx"]`

Check out https://github.com/facebook/flow/blob/master/src/common/flowConfig.ml to see how the config file is parsed/passed around

**Comment by Eyyub** [comment]
Oh I see, it's a much better idea, I will work on tonight !

**Pull request closed without merging**
