### PR TITLE
Doc: Exact object types and the spread operator

### PR DESCRIPTION
**Pull request by torarnek**
Ref #2405, document limitation and workaround of exact object types with the spread operator.

### CODE REVIEW

**Comment by samwgoldman** [comment]
I honestly would not recommend the approach documented here. The spread/exact thing is a bug and it's one I'm actively working to fix.

**Comment by avikchaudhuri** [comment]
Closing, will await @samwgoldman's fixes.

**Comment by AndrewSouthpaw** [comment]
... Except it's not fixed yet? #2405

**Comment by apolishch** [comment]
Any progress on this issue?....

**Pull request closed without merging**
