### PR TITLE
Fix libdef for Array find

### LINKED ISSUE #2191: Array.find - incorrect definition in lib/core.js
Current it is define as :
```
find(callbackfn: (value: T, index: number, array: Array<T>) => any, thisArg?: any): T;
```

The return value should be as ?T.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

### PR DESCRIPTION
**Pull request by thejameskyle**
Fixes #2191

### CODE REVIEW

**Comment by mroch** [comment]
maybe it should be `T | undefined`?

**Comment by mroch** [comment]
this seems to have broken the tests

**Comment by thejameskyle** [comment]
I was still unable to run the tests locally when I opened this, I was just gonna see what travis told me

**Comment by gabelevi** [comment]
Did you mean `| void`?

**Comment by gabelevi** [comment]
I'll fix it!

**Comment by gabelevi** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-5** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3722597) to review internal test results.

**Pull request closed without merging**
