### PR TITLE
semicolon is optional - unless computed

### PR DESCRIPTION
**Pull request by marudor**
Closes https://github.com/facebook/flow/issues/1698 and https://github.com/facebook/flow/issues/1682

### CODE REVIEW

**Comment by marudor** [comment]
Mac Build fail can be ignored I guess?

**Comment by samwgoldman** [comment]
Can you add some tests to `src/parser/test/hardcoded_tests.js` You can run them from the `src/parser` directory via `make test-ocaml`. See #1681 and #1703 for examples of adding these tests.

**Comment by marudor** [comment]
Added 2 Parser tests.

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1585606488418478/int_phab) to review.

**Pull request closed without merging**
