### PR TITLE
Add missing ChildProcess#unref()

### PR DESCRIPTION
**Pull request by jeanlauliac**
Node.js' ChildProcess class has a barely-documented function 'unref', that does not have its own section but is described as part of the 'detached' spawn option: https://nodejs.org/api/child_process.html#child_process_options_detached.

### CODE REVIEW

**Comment by stephencelis** [comment]
May want to add `ref(): void` while you're at it!

``` js
> ChildProcess.prototype
ChildProcess {
  spawn: [Function],
  kill: [Function],
  ref: [Function],
  unref: [Function] }
```

**Comment by gabelevi** [comment]
Thanks for the contribution and sorry for the delay! This looks good to me! I'll get this merged!

**Comment by stephencelis** [comment]
@gabelevi Any chance on getting `ref()` in at the same time?

**Comment by gabelevi** [comment]
@stephencelis Sure!

**Pull request closed without merging**
