### PR TITLE
Add some Chrome definitions

### PR DESCRIPTION
**Pull request by runn1ng**
I am selfishly adding only the few APIs I am using in my apps/extensions. I do not really have time (and knowledge) to add more.

### CODE REVIEW

**Comment by runn1ng** [comment]
If you think having the definitions are OK, I will also add some tests

**Comment by vkurchatkin** [comment]
Why not use `flow-typed` for this?

**Comment by runn1ng** [comment]
I am not entirely sure where to put it in flow-typed, since it isn't a library (as I wrote there).

And there already are node and react definitions here.

**Comment by avikchaudhuri** [comment]
@jeffmo WDYT? Where should these definitions go?

@runn1ng Depending on what @jeffmo thinks, the way you write tests might be different, so hold on.

**Comment by jeffmo** [comment]
Yea, we don't have the machinery yet for stuff like this in flow-typed. At some point we'd like to (and there is a rough idea for adding a new namespace that sits next to the `definitions/npm` namespace), but in the meantime platform-APIs are probably best suited in the core libs.

**Comment by fredemmott** [comment]
If these are committed, am I able to extend them to add additional APIs that I use that aren't in here, without rebuilding/packaging flow?

**Comment by runn1ng** [comment]
Nope, you have to rebuild flow, AFAIK.

**Comment by fredemmott** [comment]
Strongly against merging then unless this becomes complete. Merging would pretty much mean that only chrome extensions that happen to use the same APIs as you can use flow properly. There's at least one this would break that I'm aware of.

**Comment by runn1ng** [comment]
@fredemmott since Chrome is adding features pretty fast, it will probably never be complete and it will always be outdated.

But I understand what you mean, and I have no idea what to do with it.

**Comment by jeffmo** [comment]
@fredemmott: If we don't merge, aren't you still in the same situation?

To be clear: We want to address this general issue soon (via flow-typed) -- we just aren't equipped to do so quite yet. Still work to do to get there

**Comment by jeffmo** [comment]
Also note that it is always possible to *override* built-ins (you can always copy them into your own `[libs]` or `flow-typed` directory and adjust) -- just not extend them in place.

**Comment by fredemmott** [comment]
> If we don't merge, aren't you still in the same situation?

No, I'm just adding my own

> Also note that it is always possible to override built-ins (you can always copy them into your own [libs] or flow-typed directory and adjust) -- just not extend them in place.

That might mean this isn't a problem - no duplicate definition errors like Hack does?

That said, it could be less confusing to have `chrome is undefined` than `chrome.foo is not defined`.

**Comment by gabelevi** [comment]
I'm cleaning out our old PRs. It looks like the ideal solution is for https://github.com/flowtype/flow-typed/issues/201 to be resolved. We also have been talking about trying to move some of the core flowlibs to flow-typed too. So I'm going to close this PR out for now.

If anyone disagrees or thinks that this PR should be merged, feel free to re-open and make the case.

**Pull request closed without merging**
