### PR TITLE
added HTMLAudioElement and HTMLSourceElement

### PR DESCRIPTION
**Pull request by HolgerJeromin**
I was suprised that there was VideoElement but no AudioElement and HTMLSourceElement

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Right now i have no access to a Mac or 64 bit Linux. 
So it would be nice if someone could help me fixing those tests outputs in my branch.

**Comment by HolgerJeromin** [comment]
Is there something that is missing before it can be merged?

**Comment by gabelevi** [comment]
> Is there something that is missing before it can be merged?

Nope, just the Flow team being lazy! We'll get this in. Thanks for the contribution!

**Comment by gabelevi** [comment]
@facebook-github-bot import

**Comment by HolgerJeromin** [comment]
Thank you!

**Pull request closed without merging**
