### PR TITLE
minor doc fix

### PR DESCRIPTION
**Pull request by fabiomcosta**
valu -> value

### CODE REVIEW

**Comment by mroch** [comment]
heh, that's actually the point of that example, although it's not explicitly called out. can you add some text above this code block saying something like "In this example, there's a typo in the `decrement` method."?

**Comment by samwgoldman** [comment]
<3

**Comment by fabiomcosta** [comment]
Lol Looks like someone didn't read the whole doc before sending this PR :)

**Comment by mroch** [comment]
i'm not sure how this works... i'm going to close this, assuming you can reopen it if you update it.

**Comment by fabiomcosta** [comment]
I can always open a new one, thx and sorry for the lack of updates

**Pull request closed without merging**
