### PR TITLE
Break/continue conditional control flow

### LINKED ISSUE #4088: Breaks and control flow analysis
I would expect the following code to typecheck without error: 

```js
/* @flow */

const bool: boolean = false;

while (true) {
  let a;
  
  if (bool) {
    a = 5;
  } else {
    break;
  }
  
  numbersOnly(a);
}

function numbersOnly(n: number) {
  console.log(n);
}
```

By the time `numbersOnly(a)` is reached, `a` has been initialized. The other option is we break out of the while loop. However instead you get the error:

```
14:   numbersOnly(a);
                  ^ possibly uninitialized variable. This type is incompatible with the expected param type of
17: function numbersOnly(n: number) {
                            ^ number
```

Is this a bug, or am I missing something?

[flow.org try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMAjOOGALn0KwEMA7MAXjCgpgGdMBudBACwEsswAFNgBOAV0wBKMAG9UYMFlwUO8uWB5RBBIlNnz5FOmACsKsAF8wmFphlr5eYZgoBrM+bVqqogLZ5MwswA8lQwAJ4CFBIcHqhQolQAxtg8cDTefgHBoRFUpBn+wrpqiWnMRJgAdPAA5gJU0ajmQA)

### PR DESCRIPTION
**Pull request by goodmind**
Fixes #4088

### CODE REVIEW

**Comment by goodmind** [comment]
Ping @mvitousek

**Comment by gkz** [comment]
All tests cases in this PR now pass (or error) as expected: https://flow.org/try/#0CYUwxgNghgTiAEA3W8BGB7dEBcbMRCgDsAoEgMwFciwAXAS3SPnIEYAKASngG8T54AdwAW9AvHa0YlENz4CBBWvCj8F9chIxY5ahSvgBeeAFY98AL7wQEAM4J5+tHCgBrcxfMBuCVFxFKAFtUEBhuAHpw+HR3AU9PCmo6RmZyACYuXjU-IVFxSWlZLP0lFXMNLXxdJwNjM30rG3tip1QXVxUvD29ffyCQsPhI6NjLEgSqGgYmFgBmTMcRMQQCmWqFUtV9CvZtCHX9KCNTD2s7B3MBMCYGAJBu-R92HIDg0IiomLV4sknkmfIABYFmocLllhIpGsWooQMotupNLsqjCFEc6qcmhcatciLcZPAIA8FE8Xv13kNPqMfokpikWCYQQIlvkoUVHLD4eUkXsDmjjvUFI1zqiBDtec5CKM4j1nn03oNhqEYOgYN9xr8ktNUoz1mCWSs2XzNtzKjpRbUTg0zs0OYizft4Lj8QgiQ1ZWSFR9rDAVWqZRMtfTyAA2JkqXAGyGFY1wsrbHkou0CdFWoU27FOMFtKWErrux69eCvAbe5Wq9UWIA

**Pull request closed without merging**
