### PR TITLE
Fixed opam-depext command example

### PR DESCRIPTION
**Pull request by evantorrie**

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by mroch** [comment]
`opam depext` without the dash works for me since `opam-depext` is some sort of opam plugin (I'm not familiar with opam plugins). perhaps it is like git, where `git-foo` commands can be run as `git foo`?

what version of opam are you using?

**Comment by gabelevi** [comment]
Thanks for the contribution!

[The opam docs](https://opam.ocaml.org/doc/FAQ.html#Somepackagefailduringcompilationcomplainingaboutmissingdependenciesquotm4quotquotlibgtkquotetc) do use `opam depext` so I might leave it be for now. If you think I'm wrong, let me know why and I'll reopen!

**Pull request closed without merging**
