### PR TITLE
Fix childprocess

### PR DESCRIPTION
**Pull request by skovhus**
This fixes https://github.com/facebook/flow/issues/2824

I would wait merging it before https://github.com/nodejs/node/pull/9637 has been approved.

### CODE REVIEW

**Comment by skovhus** [comment]
The pull request on node has been merged. So this pull should be ready now.

**Comment by skovhus** [comment]
Not sure if this pull request should be merged first: https://github.com/facebook/flow/pull/2567

**Comment by skovhus** [comment]
@mroch Any thing I can do to help?

**Comment by gabelevi** [comment]
Sorry for the delay! I've rebased this on the other work and made sure that `execSync`, `execFileSync` and `spawnSync` all can now take a `string` as well. I'll get this merged ASAP!

**Pull request closed without merging**
