### PR TITLE
add WebGL 1.0 types

### LINKED ISSUE #477: Missing declarations for WebGLRenderingContext
I intend to submit a PR with my own declarations soonish. I'm auto-generating them from https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl.

### PR DESCRIPTION
**Pull request by gre**
fixes #477

i've carefully followed https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl

### CODE REVIEW

**Comment by gre** [comment]
there is one unperfect thing in my current definition:

```
WebGLRenderingContext.LINEAR
```

does pass (it's a static field in the spec).

but

```
gl.LINEAR
```

**is valid** and widely used code but won't work (property not found) because it's a static not part of the instance.

Should I duplicate the field in both the class and the instance, or is there a smart way?


**BTW, this is exactly the same on `Node`** :

https://flowtype.org/try/#0G4QwTgBAJgvFD2BjArgWwKYDsAuA6RY6I26AogDboY4AUARFAJbB0CUAUFLqQDKkCypAHIAVAPpCA8gBFSnfPEwBnbGGSJs8MNz6DREmaSA

both should be valid

**Comment by gre** [comment]
i've duplicated the webgl statics into fields. seems to work fine.

**Comment by gre** [comment]
Can you guys take a look at accepting this PR ?
I can't wait to have this shipped in flow for bunch of GL libs I have.

Thanks

**Comment by gre** [comment]
🙏 please

**Comment by Lein4d** [comment]
Here's another guy waiting impatiently for this PR to be accepted :)

**Comment by thejameskyle** [comment]
You have a number of failing tests: https://travis-ci.org/facebook/flow/jobs/173626828#L724

**Comment by gre** [comment]
as far as I understand, the failing tests are just line number changes right?

It's all about file number changes in dom.js, because I added lines in that file.

example

```diff
-    function type. Callable signature not found in. See lib: dom.js:1906
+    function type. Callable signature not found in. See lib: dom.js:2789
```

**Comment by thejameskyle** [comment]
I'll do it on my end, but to re-record those you just need to do:

```sh
# first: https://github.com/facebook/flow/tree/master#building-flow
make build
./runtests.sh bin/flow    # check that everything is just line number changes
./runtests.sh -r bin/flow # re-record tests
./runtests.sh bin/flow    # check it again to make sure everything worked.
```

**Comment by thejameskyle** [comment]
Oh you did it. Cool, but there's now a conflict. Can you rebase and retry?

**Comment by mroch** [comment]
I typically just do `./runtests.sh -r bin/flow` and `git diff` to make sure it only made line number changes. `-r` should be pretty reliable, and travis would catch it if something went horribly wrong :)

**Comment by gre** [comment]
I've rebased my branch, but for some reason, the test are still pending, mmh

**Pull request closed without merging**
