### PR TITLE
Change readonly collection types to co-variant.

### PR DESCRIPTION
**Pull request by nmn**
I'm not sure why these weren't co-variant to begin with.

### CODE REVIEW

**Comment by TrySound** [comment]
https://github.com/facebook/flow/releases/tag/v0.86.0
> Added core types $ReadOnlyMap, $ReadOnlyWeakMap, $ReadOnlySet, and $ReadOnlyWeakSet. These types and their mutable counterparts mostly follow the pattern of $ReadOnlyArray and Array: the read-only parent class provides non-mutating methods, and the usual mutable class extends it. Unlike $ReadOnlyArray, the new types are invariant in their type parameters.

**Comment by jbrown215** [comment]
@nmn: `V` can be covariant in the maps, but both `K` in the maps and `T` in the sets appear contravariantly in the signatures of the data structures. Flow doesn't check variance annotations in libdefs (though we should), which is why this isn't an error.

There's still is a way to make the type parameters covariant, though. @wchargin suggested that we can make `get` and `has` accept `mixed` as an argument so that `K` and `T` don't appear in contravariant positions.

**Comment by goodmind** [comment]
I consider making only `V` covariant, this is what Kotlin does

**Comment by SamChou19815** [comment]
We already made all of the `V` tparams covariant

**Pull request closed without merging**
