### PR TITLE
lib/node.js: stream: Allow Uint8Array in a few places.

### PR DESCRIPTION
**Pull request by cakoose**
Support for Uint8Array was added in Node 8.

### CODE REVIEW

**Comment by fishythefish** [comment]
This change causes too many type errors in the libdefs. You can see these by running the tests, for example. You'll most likely have to update the libdefs for `Uint8Array` support everywhere, not just in a few places.

**Comment by cakoose** [comment]
@fishythefish: I updated the method signatures for the `stream.Duplex` and `net.Socket` subclasses.

BTW, it seems strange that the subclasses re-declare all the base class's methods.  Maybe it would be better to omit them and just inherit?

**Comment by cakoose** [comment]
@fishythefish: Can you take a look at the updated diff?

**Comment by cakoose** [comment]
**Docs**

- `net$Socket`: [`.end`](https://nodejs.org/api/net.html#net_socket_end_data_encoding_callback), [`.write`](https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback)
- `stream$Readable`: [`.unshift`](https://nodejs.org/api/stream.html#stream_readable_unshift_chunk), [`.push`](https://nodejs.org/api/stream.html#stream_readable_push_chunk_encoding)
- `stream$Writeable`: [`.end`](https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback), [`.write`](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback)
- `stream$Duplex`: has `.end` and `.write` because it [extends `stream$Writable`](https://nodejs.org/api/stream.html#stream_class_stream_duplex)

**Callback function type**

The base class (`stream$Writeable`) uses `Function` and the derived classes (`stream$Duplex` and `net$Socket`) use `(data: any) => void`.  I changed them all to `Function` to be consistent.  Options:
1. Leave them as they were.  Maybe it was intentional that the derived classes had slightly different signatures?
2. Remove the signatures from the derived classes entirely.  And then perhaps change the base class to use `(data: any) => void`.

**Comment by nmote** [comment]
Thanks, I'll take a look at the docs when I get a chance, and assuming they match, we're good there.

For now, could you do #1 for the callbacks? I think we should switch the base classes to use the safer callback (and even better would be to get rid of `any` here altogether), but I think those changes belong in another PR. This one is close to merging so I wouldn't want to delay it while code elsewhere is perfected.

**Comment by cakoose** [comment]
Changed the callback type and rebased.

**Pull request closed without merging**
