### PR TITLE
Add brew packages to README.md

### PR DESCRIPTION
**Pull request by arknave**
List the brew prerequisites for building flow on OSX.

### CODE REVIEW

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by gabelevi** [comment]
@facebook-github-bot shipit

**Comment by gabelevi** [comment]
Hopefully this time it works...

**Comment by gabelevi** [comment]
And thanks for adding this in!

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/508461546006000/int_phab) to review.

**Pull request closed without merging**
