### PR TITLE
Promises should have optional parameters

### PR DESCRIPTION
**Pull request by runn1ng**

### CODE REVIEW

**Comment by runn1ng** [comment]
(signed the CLA now)

**Comment by runn1ng** [comment]
I am now not sure if it's correct.

The parameter should be optional only when R is void. However, I am not sure how to write that

**Comment by samwgoldman** [comment]
This feels wrong to me. It would be sad to lose the type checking that promise() is invoked with a value. Making this optional means that Promise<T> becomes Promise<T?> always.

**Comment by runn1ng** [comment]
@samwgoldman : yeah, but the current state doesn't allow you to resolve an empty promise

So you cannot define a promise that's not returning anything, unless you write `resolve(undefined)`. 

And you can have a promise that's not returning anything (Promise<void>), and it makes sense to have it.

And, by the way, in the current code, you *already* can do `Promise.resolve()` (line 357).

I am not sure how to do this ellegantly.

**Comment by runn1ng** [comment]
In other words, because of non-option, I had to change several

     resolve()

in my codebase to

    resolve(undefined)

even when I return `Promise<void>`.

**Comment by runn1ng** [comment]
(but it broke unit tests, haha.)

**Comment by samwgoldman** [comment]
Well, for what it's worth, [TypeScript's definition for Promises](https://github.com/Microsoft/TypeScript/blob/cc078653be56d38d84ffd4010e2d208eb3596ba0/bin/lib.es6.d.ts#L4807) does indicate that the argument to `resolve` is optional.

**Comment by samwgoldman** [comment]
I think this PR might be unnecessary after some recent changes to how `void` parameters are handled.

Here's an example:

```javascript
/* @flow */

function test(x: void) {
  return x;
}

// Even though test is declared to accept a parameter, this is OK
test()
```

`Promise<void>`'s `resolve` callback should have the same behavior.

**Comment by runn1ng** [comment]
That's great. I will try it on master branch and close this later.

**Comment by samwgoldman** [comment]
@runn1ng I just tried this out and I was able to run the following code without issue. Please reopen if you think there is still work to be done here:

```javascript
function f(b) {
  return new Promise((resolve, reject) => {
    if (b) {
      resolve()
    } else {
      reject()
    }
  });
}
```

**Comment by runn1ng** [comment]
yep, works, great! Your work on this project is awesome, it is more mature every day!

**Pull request closed without merging**
