### PR TITLE
fix: allow postMessage take array of transferables

### PR DESCRIPTION
**Pull request by Gozala**

### CODE REVIEW

**Comment by goodmind** [comment]
@Gozala isn't array already iterable?

**Comment by Gozala** [comment]
> @Gozala isn't array already iterable?

It is `Iterable` but not an `Iterator` which is what current typedefs expect.

**Comment by goodmind** [comment]
Maybe Iterable was intended, w3c defines it as `sequence<T>`, maybe Transferable also can be implemented

**Comment by nmote** [comment]
Closing as this isn't backed up by docs. Feel free to reopen/create a new one if this is still important.

**Pull request closed without merging**
