### PR TITLE
Support infinite loops as abnormal control flow

### PR DESCRIPTION
**Pull request by goodmind**
Related PR: https://github.com/facebook/flow/pull/2806

Related Issues:
https://github.com/facebook/flow/issues/3793
https://github.com/facebook/flow/issues/3366
https://github.com/facebook/flow/issues/4088

### CODE REVIEW

**Comment by jbrown215** [comment]
I don't think Flow should be in the business of determining whether a loop will terminate or not. Is there a legitimate use case for this functionality? Currently, Flow will check the body of the loop even if it will never run, so we don't miss any errors.

**Comment by goodmind** [comment]
@jbrown215 I don't get it why flow can't know with literal boolean value that loop will never terminate

**Comment by Bannerets** [comment]
Also note that TypeScript does such analysis

**Comment by goodmind** [comment]
I found this because I was writing docs for `empty` type (https://github.com/facebook/flow/pull/7655) and was surprised that infinite loop function doesn't infer `empty`, but `void`.

**Comment by jbrown215** [comment]
> was surprised that infinite loop function doesn't infer empty, but void

Right, that's because the function has no explicit return. `void` is an entirely reasonable type to statically assign as the return type of that function.

> Also note that TypeScript does such analysis

We shouldn't do things just because TypeScript does them. We should do things because it helps people write better and safer JS. Does this feature really do that?

Also, should it detect `while (true || false)`, or `while (true && true)`, etc. ? Where should we draw the line?

**Comment by goodmind** [comment]
It should detect them only if one of operands is true literal. I mean infinite loop doesn't return, you can't get void (undefined) as return value

**Comment by jbrown215** [comment]
> And something like this would be wrong type

but it wouldn't, since `empty` is a subtype of everything, so any annotation there would pass type checking.

> I mean infinite loop doesn't return, you can't get void (undefined) as return value

Sure, but you also can't get something of type `empty` because nothing inhabits that type. I just don't see what value this provides.

**Comment by jbrown215** [comment]
@Bannerets 
> Also note that TypeScript does such analysis

[That doesn't seem to be true?](https://www.typescriptlang.org/play/index.html#src=function%20f()%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%20%20return%20''%3B%0A%7D%0A%0A(f()%20as%20number)%3B)

**Comment by Bannerets** [comment]
@jbrown215 You need to explicitly annotate the return value as `never`.

[See examples](https://www.typescriptlang.org/play/index.html#src=function%20f()%3A%20never%20%7B%0A%20%20while%20(true)%20%7B%20%7D%0A%20%20return%20''%0A%7D%0A%0A(f()%20as%20number)%3B%0A%0Adeclare%20function%20sideEffect()%3A%20boolean%0Adeclare%20var%20b%3A%20boolean%0A%0Afunction%20f0()%3A%20string%20%7B%20%2F%2F%20ok%0A%20%20while%20(true)%20%7B%0A%20%20%20%20return%20''%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20loop0()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20while%20(true)%20%7B%0A%20%20%20%20break%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20loop1()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20a%3A%20while%20(true)%20%7B%0A%20%20%20%20while%20(true)%20%7B%0A%20%20%20%20%20%20break%20a%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0A%0Afunction%20loop1_1()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20a%3A%20while%20(true)%20%7B%0A%20%20%20%20b%3A%20while%20(true)%20%7B%0A%20%20%20%20%20%20break%20b%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20loop2()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20a%3A%20while%20(true)%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20loop3()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20while%20(true)%20%7B%20%7D%0A%7D%0A%0Afunction%20loop4()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20while%20(sideEffect()%20%7C%7C%20true)%20%7B%20%7D%0A%7D%0A%0Afunction%20loop5()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20while%20(true%20%26%26%20true)%20%7B%20%7D%0A%7D%0A%0Afunction%20loop6()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20while%20(true%20%26%26%20false)%20%7B%20%7D%0A%7D%0A%0Afunction%20loop7()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20while%20(true%20%7C%7C%20false)%20%7B%20%7D%0A%7D%0A%0Afunction%20loop8()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20if%20(b)%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%7D%20else%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20loop9()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20if%20(b)%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20loop10()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20l%3A%20while%20(true)%20%7B%0A%20%20%20%20continue%20l%0A%20%20%20%20break%20l%20%2F%2F%20'Unreachable'%20in%20Flow%0A%20%20%7D%0A%7D%0A%0Afunction%20for0()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20for%20(%3B%20%3B)%20%7B%20%7D%0A%7D%0A%0Afunction%20for1()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20for%20(%3B%20true%3B)%20%7B%20%7D%0A%7D%0A%0Afunction%20for2()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20for%20(%3B%20sideEffect()%20%7C%7C%20true%3B)%20%7B%20%7D%0A%7D%0A%0Afunction%20for3()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20for%20(%3B%20false%3B)%20%7B%20%7D%0A%7D%0A%0Afunction%20for4()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20a%3A%20for%20(%3B%20%3B)%20%7B%0A%20%20%20%20break%20a%0A%20%20%7D%0A%7D%0A%0Afunction%20doWhile0()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20do%20%7B%0A%0A%20%20%7D%20while%20(true)%0A%7D%0A%0Afunction%20doWhile1()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20do%20%7B%0A%0A%20%20%7D%20while%20(true%20%26%26%20true)%0A%7D%0A%0Afunction%20doWhile2()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20do%20%7B%0A%0A%20%20%7D%20while%20(sideEffect()%20%7C%7C%20true)%0A%7D%0A%0Afunction%20doWhile3()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20do%20%7B%0A%20%20%20%20break%0A%20%20%7D%20while%20(true)%0A%7D%0A%0Afunction%20doWhile4()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20l%3A%20do%20%7B%0A%20%20%20%20while%20(true)%20%7B%0A%20%20%20%20%20%20break%20l%0A%20%20%20%20%7D%0A%20%20%7D%20while%20(true)%0A%7D%0A%0A%0A%2F%2F%20Tests%20with%20%60if%20(%3Cboolean-literal%3E)%60%0A%0Afunction%20if0()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20if%20(true)%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20if1()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20if%20(false)%20%7B%0A%20%20%20%20while%20(true)%20%7B%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20if2()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20if%20(true)%20%7B%0A%20%20%20%20do%20%7B%0A%0A%20%20%20%20%7D%20while%20(true)%0A%20%20%7D%0A%7D%0A%0Afunction%20if3()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20while%20(true)%20%7B%0A%20%20%20%20if%20(false)%20break%0A%20%20%7D%0A%7D%0A%0Afunction%20if4()%3A%20never%20%7B%20%2F%2F%20error%0A%20%20a%3A%20while%20(true)%20%7B%0A%20%20%20%20while%20(true)%20%7B%0A%20%20%20%20%20%20if%20(true)%0A%20%20%20%20%20%20%20%20break%20a%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20if5()%3A%20never%20%7B%20%2F%2F%20ok%0A%20%20a%3A%20while%20(true)%20%7B%0A%20%20%20%20while%20(true)%20%7B%0A%20%20%20%20%20%20if%20(false)%0A%20%20%20%20%20%20%20%20break%20a%0A%20%20%20%20%7D%0A%20%20%7D)

**Comment by jbrown215** [comment]
Either way, I still don't see what use case this supports. Is there some kind of (non-contrived-)pattern or code that you need this to be able to check?

**Comment by Bannerets** [comment]
In my experience `while(true)` is pretty frequently used construct.

One example:

```js
const merge = (_t1: leftist, _t2: leftist): leftist => {
  let t2
  let t1
  let k1
  let l
  let merged
  let rank_left
  let rank_right
  while (true) {
    t2 = _t2
    t1 = _t1
    if (t1) {
      if (t2) {
        k1 = t1.value
        l = t1.left
        if (layerComparator(k1, t2.value)) {
          _t2 = t1
          _t1 = t2
          continue
        }
        merged = merge(t1.right, t2)
        rank_left = l?.rank ?? 0
        rank_right = merged?.rank ?? 0
        if (rank_left >= rank_right) {
          return new Leftist(k1, rank_right + 1, l, merged)
        }
        return new Leftist(k1, rank_left + 1, merged, l)
      }
      return t1
    }
    return t2
  }
  /*::return _t1*/
}
```

([source](https://github.com/zerobias/effector/blob/32dc73285f7e146a4513658d80fac4dd52cff012/src/effector/kernel/kernel.js#L65))

Of course, one can just write `/*:: throw Error('unreachable') */` (or without `/*:: */`) after the loop. This is needed just to not force developers insert useless `throw`s in their valid code.

But I personally don't see much benefit in it. If it too difficult to add into Flow, maybe it would be better to do other more important tasks.

**Comment by jbrown215** [comment]
Ah, very interesting. That's exactly the kind of thing I was looking for to justify this PR.

**Pull request closed without merging**
