### PR TITLE
Add typings for ReactDOM.hydrate()

### PR DESCRIPTION
**Pull request by filipstefansson**
Fixes issue #5035 by adding typings for the new `ReactDOM.hydrate()` function.

### CODE REVIEW

**Comment by gabelevi** [comment]
Looks good to me! I'll get this imported and the tests re-recorded.

**Comment by max-mykhailenko** [comment]
When do you plan to merge this one?

**Comment by JustFly1984** [comment]
Guys, this issue killed my day. Can somebody fix that? feels like flow doesn't provide. it is 2018 already.

**Comment by callumlocke** [comment]
@gabelevi sorry to nag, but can this be merged in yet?

**Comment by callumlocke** [comment]
Good bot

**Pull request closed without merging**
