### PR TITLE
Add KeyboardEvent type

### PR DESCRIPTION
**Pull request by JustinTulloss**
Extends UIEvent with the keyboard event attributes as defined by MDN.

### CODE REVIEW

**Comment by mroch** [comment]
i think the test failures actually are relevant. the tests just run `flow check` and compare the current output to the expected output, which includes line numbers. since this shifts stuff down in `dom.js`, the expected line numbers changed. you can `cp tests/dom/dom.out tests/dom/dom.exp` (and similar for the other failing test) to update the expected values.

**Comment by JustinTulloss** [comment]
Oh I see, that's confusing!

I'll update.

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by mroch** [comment]
thanks!

**Pull request closed without merging**
