### PR TITLE
Add missing Buffer method declarations

### LINKED ISSUE #1862: Missing declarations for node.js Buffer, variable byte length read/write Uint & Int
The following declarations are missing, from the node.js Buffer type declaration for variable byte length signed and unsigned integers, for both little and big endian.

### Missing method declarations

- [`readUIntLE(offset, byteLength, noAssert?)`][readUIntLE]
- [`readUIntBE(offset, byteLength, noAssert?)`][readUIntBE]
- [`readIntLE(offset, byteLength, noAssert?)`][readIntLE]
- [`readIntBE(offset, byteLength, noAssert?)`][readIntBE]
- [`writeUIntLE(value, offset, byteLength, noAssert?)`][writeUIntLE]
- [`writeUIntBE(value, offset, byteLength, noAssert?)`][writeUIntBE]
- [`writeIntLE(value, offset, byteLength, noAssert?)`][writeIntLE]
- [`writeIntBE(value, offset, byteLength, noAssert?)`][writeIntBE]

These methods have been part of the buffer type since node 1.0.0, I have written a PR @ #1849 

[readIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_readintle_offset_bytelength_noassert
[readIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_readintbe_offset_bytelength_noassert
[readUIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_readuintle_offset_bytelength_noassert
[readUIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_readuintbe_offset_bytelength_noassert
[writeIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_writeintle_value_offset_bytelength_noassert
[writeIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_writeintbe_value_offset_bytelength_noassert
[writeUIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_writeuintle_value_offset_bytelength_noassert
[writeUIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_writeuintbe_value_offset_bytelength_noassert

### PR DESCRIPTION
**Pull request by AKST**
Fixes #1862 #1864

### Variable byte length BE/LE read/write for UInt & Int

- [`readUIntLE(offset, byteLength, noAssert?)`][readUIntLE]
- [`readUIntBE(offset, byteLength, noAssert?)`][readUIntBE]
- [`readIntLE(offset, byteLength, noAssert?)`][readIntLE]
- [`readIntBE(offset, byteLength, noAssert?)`][readIntBE]
- [`writeUIntLE(value, offset, byteLength, noAssert?)`][writeUIntLE]
- [`writeUIntBE(value, offset, byteLength, noAssert?)`][writeUIntBE]
- [`writeIntLE(value, offset, byteLength, noAssert?)`][writeIntLE]
- [`writeIntBE(value, offset, byteLength, noAssert?)`][writeIntBE]

The documentation doesn't say much about the return types of these methods, so [I checked the source][readUIntLE implementation] of the implementations and they do infact return integers. Also I'm unaware of any backwards compatibility guarantees made by flow, but these methods were added to  node as of `v1.0.0` (mentioned under the signature of each of the methods in the docs).

screenshot 2016-05-26 21 11 51

### Static alloc

Implementation of method [here][alloc implementation].

- [`static alloc(size, fill?, encoding?)`][alloc]

This method is only available as of node `v5.10.0`

screenshot 2016-05-29 04 39 51

------

## Meta

This is my first time contributing to this project and I'm abit native about the contribution process, however I've read the `CONTRIBUTING.md` file and signed the contributor license thing. But if implementing this is a bit more involved than the submitted code, I totally understand if you prefer to close my PR and make an issue about it 😄 *(Edit: I have since made an issue about it)*

That said I just had the file open in my browser and figured I may as well make the changes I assume are required.

[readIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_readintle_offset_bytelength_noassert
[readIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_readintbe_offset_bytelength_noassert
[readUIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_readuintle_offset_bytelength_noassert
[readUIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_readuintbe_offset_bytelength_noassert
[writeIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_writeintle_value_offset_bytelength_noassert
[writeIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_writeintbe_value_offset_bytelength_noassert
[writeUIntLE]: https://nodejs.org/api/buffer.html#buffer_buf_writeuintle_value_offset_bytelength_noassert
[writeUIntBE]: https://nodejs.org/api/buffer.html#buffer_buf_writeuintbe_value_offset_bytelength_noassert
[alloc]: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding

[readUIntLE implementation]: https://github.com/nodejs/node/blob/05e2acb428047174fc201158ac859d20c2ece1dd/lib/buffer.js#L834
[alloc implementation]: https://github.com/nodejs/node/blob/05e2acb428047174fc201158ac859d20c2ece1dd/lib/buffer.js#L154

### CODE REVIEW

**Comment by AKST** [comment]
Okay looks like I didn't write tests... I'mma download the source and write those tests

**Comment by AKST** [comment]
Okay looks like the failing tests are related to error messages, and their associated line number, which were out of sync after made changes added to `lib/tests.js`.

**Comment by AKST** [comment]
Okay another test, failed but on an operating system I don't have

screenshot 2016-05-26 22 16 10

Possibly a nondeterministic test?

**Comment by AKST** [comment]
I've extended this PR to include a declaration for the static method `alloc` for buffer, I would have made a seperate PR but if the changes were in seperate PR's they would have conflicted since they both increment line numbers in `test/node_tests/nodes_test.exp` so since they're both related, I've just put them in the same PR.

**Comment by mroch** [comment]
looks good to me, thanks!

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1025638577520370/int_phab) to review.

**Pull request closed without merging**
