### PR TITLE
Add getMaxListeners to node's process object.

### PR DESCRIPTION
**Pull request by cpojer**
See https://nodejs.org/api/events.html#events_emitter_getmaxlisteners

### CODE REVIEW

**Comment by mroch** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/972014286230887/int_phab) to review.

**Comment by mroch** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/972014286230887/int_phab) to review.

**Pull request closed without merging**
