### PR TITLE
Add "stream" parameter to createMediaStreamSource

### PR DESCRIPTION
**Pull request by pinkstrings**
createMediaStreamSource should expect a parameter:

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource

Issue: https://github.com/facebook/flow/issues/4095

### CODE REVIEW

**Comment by pinkstrings** [comment]
I know you guys are busy, just wanted to touch base on this.

**Comment by randallb** [comment]
@pinkstrings can you rebase? I appreciate this and hope by rebasing it'll get merged.

**Comment by pinkstrings** [comment]
Fingers crossed!

**Comment by pinkstrings** [comment]
Fixed in 469518a

**Pull request closed without merging**
