### PR TITLE
[DOCS] document react.runtime option

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by Brianzchen** [comment]
Should we add it here too?
https://flow.org/en/docs/config/options/

**Comment by jbrown215** [comment]
@Brianzchen It's already documented there: https://flow.org/en/docs/config/options/#toc-react-runtime-automatic-classic

I'm ok with duplicating it on the React page for visibility.

**Comment by FezVrasta** [comment]
Using the search functionality on the documentation and searching for `jsx` and `runtime` returns no results

**Comment by Brianzchen** [comment]
> Using the search functionality on the documentation and searching for `jsx` or `runtime` returns no results

@FezVrasta I've also found it quite unusable https://github.com/facebook/flow/issues/8478

**Pull request closed without merging**
