### PR TITLE
Expand Node types definitions for append/replace/removeChild and insertBefore.

### PR DESCRIPTION
**Pull request by loganfsmyth**
Ran into this while exploring adding flow to a project. Shouldn't break any existing code AFAIK.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by loganfsmyth** [comment]
Definitely signed the CLA ~20 minutes ago?

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by loganfsmyth** [comment]
I added another commit with two more cases of the same issue that I found after I created the PR.

**Comment by mroch** [comment]
looks good to me, thanks!

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3924403).

**Pull request closed without merging**
