### PR TITLE
add IFrame contentWindow and contentDocument

### PR DESCRIPTION
**Pull request by xuorig**
Adds missing `contentWindow` and `contentDocument` attributes to `HTMLIFrameElement`.

Not sure if `contentWindow` should be `any` or `window` ?

### CODE REVIEW

**Comment by ahfarmer** [comment]
@xuorig I would love it if you rebased this! It's a feature I've been waiting for.

I did a little research and I can answer your question about `contentWindow`. For now, it should be `any`.

In the `bom`, `var window` is declared as type `any`: https://github.com/facebook/flow/blob/master/lib/bom.js#L39

Also FYI, in https://github.com/facebook/flow/issues/2150#issuecomment-237666689, @thejameskyle mentioned that the type for `window` should be improved. But for now it's `any`.

**Comment by xuorig** [comment]
Awesome thanks andrew ill rebase this!

**Comment by xuorig** [comment]
Rebased + ran 

```
./runtests.sh bin/flow dom
cp tests/dom/dom.out tests/dom/dom.exp
```

cc @ahfarmer @gabelevi

**Comment by msiemens** [comment]
Any news on this? Or is this stalled?

**Comment by gabelevi** [comment]
I'm not sure why we've neglected this PR for so long. Maybe because it accidentally deleted `dom.exp`. Anyway, I've imported it, fixed the test, and am waiting for another team member to review it.

@xuorig - Sorry for there being such a long delay 😞 ! A PR should never ever wait this long for a review or merge. Thanks for your contribution!

**Comment by xuorig** [comment]
No worries @gabelevi! thanks for taking the time to merge it. 💌

**Pull request closed without merging**
