### PR TITLE
Add documentation for $ObjMap

### PR DESCRIPTION
**Pull request by gabro**
This is long due.

I volunteered [some time ago](https://github.com/facebook/flow/issues/2464#issuecomment-274808633) to document advanced features, and @thejameskyle was so nice to even reach out and ask for help for the new website that saw the light yesterday.

Unfortunately "life happened" and I couldn't find the time to contribute as I thought.

Now that the new gorgeous docs are out, I feel really sorry for not having helped like I promised and I think the minimum I can do is to fill some of the remaining the gaps.

Here's the documentation for `$ObjMap`, a powerful advanced feature that many asked to explain.

Hope this helps!

### CODE REVIEW

**Comment by vkurchatkin** [comment]
I think we should postpone this until $ObjMap is fixed

**Comment by gabro** [comment]
Can you point to the specific issue?

There are some other features of flow that are bugged / crippled, but I'm not sure not documenting then is the way to go.

Maybe we can add a note in the doc, pointing the the specific issue so that people are aware and can subscribe to it if they wish?

**Comment by vkurchatkin** [comment]
https://github.com/facebook/flow/issues/2674

> There are some other features of flow that are bugged / crippled, but I'm not sure not documenting then is the way to go.

I think it's fine to keep them private for the time being. Some features have issues, but are still useful. `$ObjMap` is so broken that it's really unsafe to use it

**Comment by gabro** [comment]
Thanks. I understand your point.

Still, I think it's more beneficial to document the feature and clearly state what's broken, rather than leaving it undocumented, which doesn't prevent usage.

This is under the assumption that people are kind of used to undocumented features in Flow, so I don't think it signals that something shouldn't be used.

**Comment by vkurchatkin** [comment]
We should draw the line somewhere. What about `$Facebookism` stuff? Clearly something should stay undocumented

**Comment by gabro** [comment]
I agree a line should be drawn. My understanding is that `$ObjMap` is intended as a public API (although severely broken at the moment) and for this reason people are using it (and blogging about it) without the awareness of its current state.

Documentation with a clear warning linking to the bug report would make this better, not worse, in my opinion.

That being said, I'm far from suggesting that every `$Foo` looking type should be documented. Some internals are clearly internals, I just happen to think that `$ObjMap` is not an internal.

**Comment by vkurchatkin** [comment]
I consider `$ObjMap` unfinished, but not private. It seems that it's not going to be fixed any time soon, sadly.

**Comment by gabro** [comment]
>I consider $ObjMap unfinished, but not private. It seems that it's not going to be fixed any time soon, sadly.

Yet, this is not clear and I see people all around using it and basing libraries on it (@gcanti and @andreypopp come to mind).

I've added a warning to the documentation.

I think someone from Facebook should now chime in and decided what's the line to keep here. If the feature shouldn't be used, I'd prefer to see it removed from the public API, rather than left half-baked and undocumented.

**Comment by samwgoldman** [comment]
Thanks for doing this! Experience has shown us that it doesn't work to omit features from the documentation just because there are bugs. Instead, I think we should try to document the features with the necessary disclaimers and provisos, as @gabro has done here.

**Comment by mwalkerwells** [comment]
@gabro Unless I'm missing something obvious, some of the examples are not valid JS.
````js
// @flow

// let's write a typelevel function that takes a `() => V` and returns a `V` (its return type)
type ExtractReturnType = <V>(() => V) => V 

function run<A, O: {[key: string]: () => A}>(o: O): $ObjMap<O, ExtractReturnType> {
  return Object.keys.map(k => o[k]());
}
````
Not sure why this doesn't error either...but ``Object.keys.map`` is not a function.
````js
return Object.keys.map(k => o[k]());
````

**Comment by gabro** [comment]
Woops, yes, it should be Object.keys(o), not sure why it doesn't error :(
Thanks, I'll submit a fix later today.

--
gabriele
~ buildo

**Comment by gabro** [comment]
@mwalkerwells wow, they were more broken than I thought. Here's the fix https://github.com/facebook/flow/pull/3605 but it's troublesome that flow itself didn't catch that.

**Comment by mwalkerwells** [comment]
Yeah, pretty surprising!

That's how I rewrote it also, but was surprised when it didn't error _again_ when not calling the function within the ``Object.assign`` like so:

````js
// @flow

// let's write a typelevel function that takes a `empty => V` and returns a `V` (its return type)
type ExtractReturnType = <V>(empty => V) => V 

function run<A, O: {[key: string]: empty => A}>(o: O): $ObjMap<O, ExtractReturnType> {
  // No Error       
  return Object.keys(o).reduce((acc, k) => Object.assign(acc, { [k]: o[k] }), {});
}

// Error: Type is still "empty => number" not "number"
const foo: number = run({ foo: () => 'foo' }).foo
````
````js
12: const foo: number = run({ foo: () => 'foo' }).foo
               ^ string. This type is incompatible with
12: const foo: number = run({ foo: () => 'foo' }).foo
               ^ number
````

https://flow.org/try/#0PTAEAEDMBsHsHcBQiSmgUwC4HIDOp4AnAS03VAENRMBPAB3QwDdHRIBXAOwGNNjZO1ABYVM1CgGt0+KgAN0AWzq1QAXgB8oAGqzKnACahCWdoU4zQsnaAAUpfMcynBtBgEpEr8gFEAHpkIKXgAlEzMAFXpyVVAAHi11G0VlGjVNLTc07VBkDh4+ASMuWIBBABpQAHkALlAAbwBtKRpa3ADiTgBzAF1a5JUNUBKAX0TYWsq3WoASSoAjACsAWQo6WMqKvwCgzFCnCKjNOsRQUFQAOVhQb0JCWEJTx9OTozDBeYX0XgA6ZtwbWBub7GfTsbjoGw2ILcCoSTKDD5fTDfCi4XDETqcKHcGH1UBNXqgWAE0DDNwVOpkgDciGGyFQNzuhFqkQYoGI+DaxGg0FAACJ+qlBpx2Ao5uhCHzQJxYGI+SKxRK+YhuAI2mxYONpaLxQ8YoQuDY6hqtTZ4ZpsJBNdhSUCrbAgA

**Pull request closed without merging**
