### PR TITLE
Updated redux.md

### PR DESCRIPTION
**Pull request by johnslay**
Removed a dead resource link

### CODE REVIEW

**Comment by johnslay** [comment]
tagging @frantic in case he does not know his website is down.

**Comment by frantic** [comment]
Thanks for the heads up @johnslay!
I should get it back online today, sorry about that!
There was a DNS issue with my domain name, I'm figuring it out :)
Meanwhile you can find the source here https://github.com/frantic/frantic.github.io/blob/master/_posts/2016-05-28-using-redux-with-flow.md

**Comment by frantic** [comment]
I think I fixed it, could you please try again?

**Comment by johnslay** [comment]
Looks good, im gonna close this issue... Thanks!

**Pull request closed without merging**
