### PR TITLE
Adding React.StrictMode type

### PR DESCRIPTION
**Pull request by brunotavares**
[<React.StrictMode>](https://reactjs.org/docs/strict-mode.html) is part of the official API but we don't have a type for it yet.

[Flow Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcy1duAHS0OxXFQCi0KmioA7XAAp+9QQGVc2FPQCysACZUANKDkBXaNACUvRAB4VQjVt0GqAPjvBH6zdtx6hu7coCCgpGa0tFSkpMgOnE5+rkF2+igAbqGe3om+LgFuwaFgEVExcfY+zv6BHgAWKF7VyYVBIWFl0bHxLQV1nqQYxHLujV5DI57pGe4ARgCeVF4zOX21RR2lkd2VCQL5G4YlJKC0zLIKiMBEI7C49VTYZxfy+ATAiGNNuQc1KR4tuEdhVEEA)
```
^ Cannot get `React.StrictMode` because property `StrictMode` is missing in module `react` [1].
```

This diff: 
 - adds the API, acting just like <React.Fragment>
 - adds new tests
 - updates existing tests

Test Plan:
```
bash ./runtests.sh  bin/flow
```

### CODE REVIEW

**Comment by motiz88** [comment]
For the record / housekeeping:

- There is an older PR https://github.com/facebook/flow/pull/6078 open for this (but the current one does look more complete).
- This should close https://github.com/facebook/flow/issues/6107.
- Worth linking to https://github.com/facebook/react/issues/12553.

**Comment by cvoege** [comment]
Is there a reason this never gets merged? StrictMode came out in march and it still has no flow support in October. It's starting to make my confidence in this library slip.

**Comment by brunotavares** [comment]
@cvoege integrating with FB codebase was taking quite a bit of time and I got pulled into some other work. Thanks for the ping.

**Comment by cvoege** [comment]
Should the flow types for React be moved into flow-typed? It would prevent having to go through this many hoops to update the types for React.

**Comment by cvoege** [comment]
@brunotavares Is there any way to get facebook to notice this merge? It' simple, complete, adds working tests, and is around 7 months overdue. How can we get this merged so I can finally stop using $FlowFixMe?

**Pull request closed without merging**
