### PR TITLE
[bom] Define MutationObserverInit

### PR DESCRIPTION
**Pull request by kuy**
`MutationObserverInit` is used as an argument named `options` in `MutationObserver#observe`.
The name is borrowed from here: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#observe()

I wanted to catch a runtime error "An invalid or illegal string was specified", but I don't know how to describe the condition written in [side note](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#MutationObserverInit).

> NOTE: At the very least, childList, attributes, or characterData must be set to true. Otherwise, "An invalid or illegal string was specified" error is thrown.

### CODE REVIEW

**Comment by gabelevi** [comment]
> I wanted to catch a runtime error "An invalid or illegal string was specified", but I don't know how to describe the condition written in side note.

I suppose you could write a union, [like this](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvKmGAD5gDeYAhgFxgYBOArngDRgBGrfiRh5GAOz4BjISLHiwAX0o16TWXFES+gtl15gZAuRKUraDFsc3ydGrZMOsO3JQG50ACjpWXB3VCMMADOBkaBIXiKrMRwAJQe3lYRoXZ63NKsKVExJAmoSVlBqQJFkZnpOUR5iT5lJQHFYfVVsQlAA)

**Comment by gabelevi** [comment]
Do you want me to merge this as is, or do you want to try and do the union approach?

**Comment by kuy** [comment]
@gabelevi Thanks for replying and giving an example code of union type. I want to try the union approach.

**Comment by kuy** [comment]
Oh... I did misoperation. I'm still working on this PR.

**Pull request closed without merging**
