### PR TITLE
[typing] Improve interface and class typechecking

### LINKED ISSUE #4580: Any class type is consider a subtype of a generic indexer
Am I missing something, or is this a case where flow's analysis is unsound?

```js
function test<T>(input: {[string]: T}) {}

class Foo {
  n: number;
  b: boolean;
}

test(new Foo);
```

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygHgCoD4AUMYADiFAFyIDeA2hgE5EDmAupdgL4CU1HAUHwgAbAIZo0iAGJw41PokRhKYEAFsARinoBueYnWV1MoShFhd-Pqgz4wKAO5SZXbUA

When `Foo` is an equivalent object type, it's (correctly) an error:

```js
function test<T>(input: {[string]: T}) {}

type Foo = {
  n: number;
  b: boolean;
}

const foo: Foo = {n: 0, b: true};
test(foo);
```

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygHgCoD4AUMYADiFAFyIDeA2hgE5EDmAupdgL4CU1HAUHygBPYikQAxOHEQBean0SIwlMCAC2AIxT0A3AsQbKGqQBsUAQzB7+fCAgyJgUypOlyqyxAAYANAcpQ9CAoHHqoGPhOcFw6QA

### LINKED ISSUE #7043: Classes are unsoundly considered subtypes of objects with optional keys
A class type `C` that has no attribute by the name `attr` is unsoundly
considered by Flow to be a subtype of `{attr?: T}` for any type `T`.

[This yields `coerce`:][1]

```js
// @flow
function coerce<T, U>(t: T): U {
  class C {}
  const x: C = new C();
  const y: { box?: { value: T } } = x;
  const z: { box?: "sentinel" } = x;
  y.box = { value: t };
  if (z.box != null && z.box !== "sentinel") {
    return (z.box: empty).value;
  }
  throw new Error("Unreachable.");
}
const twelve: number = coerce("twelve"); // no type error
twelve.toFixed(); // runtime error!
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaBrAKYBOGxAPACoA0oAqgHwAUWAXKNQJScOgBvRKELQAhgGcJoAMKCAvsML4JWUAA9OcgLyg0xeLJbcA3EqJpVoAJ6cBoAEax1AfjugAbmOgpinaqDygaC66mYiFlYAXu5OrpwARBLEaLj60AnBoeE2AHRxIYKe3r6cavI5OJCgLFH5zqAAhLpoKNDQoABknaB1Bc26SSlpxBncgkoipMRYKKQEtfWaoMQAtgAOWNbcuV4+xDmKIlgAFqQIegagAKKk56QsCQxo02IYJ2IO0MS5CaaIikiaiw8FGHj8ehQqwcZEKRDIFEeILBxD+JlAID0sFAW3WxBWd1gpEQyOg4NyWFgADEcOpiAATYzozGkdC4Vb4sj3RqIIA

I noticed this in expecting `((p: Promise<{x?: string}>): {x?: string})`
to be a type error. It turns out that it has nothing to do with
`Promise`s specifically.

This is reproducible in Flow v0.83.0 (and master), and all the way back
to Flow v0.37.0, the earliest version available on Flow Try.

### LINKED ISSUE #7474: Error for optional class property despite implementing interface
Flow version: 0.93.0

## Expected behavior

1. I would expect flow not to throw an error because the class interface explicitly declares foo as an optional property.

## Actual behavior

Flow throws an error as if the property was not declared at all. In contrast, an object literal typed with the same interface or analogous type does not throw an error as the property is declared (event though its value is still `undefined`).

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAssQJ4BGeAYnHGAN6phhRsD8ALjAAKAJRgAvAD4wANzgYAJqgC+AbnSkYxAM66wAdQw4AFnACuOVuwwBbAA4w8dvLgM16TG5zWbUpHBYujhgCCbmVj6SYFh4SMZmltZs-sDAYADKkTBKYEy82BQiFlhKeFBFShIMVmCEBHAEBsmCqOFJUWwAdHxw-oHBoVhwNsKejCxsUpwa6OlgAMKWuIQAtHgAHsSOzqJwANb0vE1gcAwAVnikoR2mYNj4RGR4YsJgqCM2vanoj4QkchgWiTGwAFToDgoXB4fSEogkMnkihUcx4ASCITAxBgujgADlRmxhCDvGwIVCZhw5qgFstSk8NttdsVDsc+AQzpdrrcImAcJDXm0cXjCd8+pogA

Very contrived example of how this can causes headaches in practice:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAglhgLbExgDeqYYWx9eA-AFxgAzjgLYA5gBp2YHAE8ADnkEixWKTIQALONXqUAFAEoVoidIC+AbnSkYxIULC0GTMAwUw8PXE5p1GZjYOeSUwAF4wAHJiLDBY1xgomw4ZUjgsVQBXUhw4AgMuHgFhM3UjVhkQrQwhADoiikjGlLALGU0dPUMK4I4wdMycdz1qCLAAIkp4+kmwAGpZGvrQikWJuonW1P73KDADHGWG7jxe1ABIDkGRMHo5ADlTyidIiYBZOU5T9ycJhaWtROPABGy2VX6EI4BDwOCyBDi9yePBeoLmiwwo22bQhEJhcIRI3o1Fa7XaqDsDicABE4OIwHgAB74LAAEycLkClRCiia0WIYFZdOSqHJlMcYAAMhgAF7EAishnMvBsjkBNx9VbjGJgGCy+WskVijK3BKBV5gADaWDwSFp4gMUQAytwokZJJxbVL9QrHQBxeVyN0em1ITlMAC6NlQZqY9Sg+QAomQtAYDLGYBVwgA+bkDE1wLx1eAOjN1bS6fTGIw2Cw1oA

### LINKED ISSUE #8080: Optional property implements
Flow version: 0.107.0

Originally from https://github.com/joarwilk/flowgen/issues/99

Related issue https://github.com/facebook/flow/issues/7474

## Expected behavior

`No errors`

## Actual behavior

```
6:   endpoints?: Array<string>;
                 ^ Cannot implement `A` [1] with `B` because undefined [2] is incompatible with array type [3] in property `endpoints`.
References:
5: declare class B implements A {
                              ^ [1]
6:   endpoints?: Array<string>;
                 ^ [2]
2:   endpoints?: Array<string>;
                 ^ [3]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYOwLgpgTgZghgYwgAgILIN4ChnIiAEwAcB7UMAZwH4AuNKKOATwB4KwpQBzAPgG4sAXxzIsBCAgA2cKCilwKFZACFkwALZFJEdfkppMI-MTLhqdVA2ZsO3fkKxA

### PR DESCRIPTION
**Pull request by goodmind**
Fixes #8080
Fixes #7043
Fixes #4580
Fixes #7474

Changes:

```js
interface A {
  foo?: number;
}

declare class B implements A {
  foo: number; // error, foo in A should be covariant
}

const x: A = {} // error, optional properties should be implemented
const y: A = {x: 1} // error, optional properties should be implemented

declare class D implements A { // error, optional properties should be implemented

}

class U {}

const z: A = new U() // error, optional properties should be implemented
```

### CODE REVIEW

**Comment by goodmind** [comment]
This maybe looks like too much breaking changes, but idk how to fix unsoundness of classes without it

**Comment by fedgrant** [comment]
Wouldn't this also solve https://github.com/facebook/flow/issues/650? Is there anything that can be done to move this forward?

**Comment by SamChou19815** [comment]
Closing since all original issues are already fixed, and we revamped some interface typing, so most of the code no longer applies.

**Pull request closed without merging**
