### PR TITLE
fix libdef for navigator.mediaDevices.getUserMedia

### LINKED ISSUE #8160: Having problems with MediaStreamConstraints
I'm new to flow, so this may be my error, but I tried a bunch of combinations and still can't get this to work:

      const constraints : MediaStreamConstraints = { video: { facingMode: "environment" } };

I was able to reproduce here:  https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gDCcWAzjgcdgCIDyAsgMoPYDmACsUYBbPPgK0wAb1RgweAB5kcAfgBcYegT5gAPpp5ZeAbQC6AbllgMAEzzEY6g9qN7nfM5YC+6bOJLkYOx4NhjEACqMpADW1HQMTLicYtJWcgF87HB2Tlo6+nlGZm5xWolsXIYCQsSi4rTevriEARTBoRFRsTRlfpKK+Fg2ku1hkWTd8Yx+yTipcsQ2AG7EWOQ2TgCCBIwAngA8o50TpQkzYgB8jag4uwAObSFh3AT2wqfTuJIAvPNgxABXUJwJwAIzgcBg9iwbiO4xiH0SOAaViWtjwII04Mh0NhT2OCJ6Zy+ljkD0IAEk7LgMLdclVSWAAHQs1A+VCkIlgTlTJGSDRHF5vRF9MC-KRgNF2OAaCUZIxZOwaABEeCwaIINFEuGVYC8essQA

I extracted only the relevant parts from here:  https://github.com/facebook/flow/blob/v0.104.0/lib/bom.js#L1124

To my untrained eye, I would have thought the string would be fine.

### PR DESCRIPTION
**Pull request by thecotne**
fixes #8160

### CODE REVIEW

**Comment by gitonthescene** [comment]
Awesome!  Thanks!

**Comment by gkz** [comment]
Thanks for the PR!

Can you change the tests to be in `tests/` (and in that format) instead of `newtests/`? 

Unless they need some special functionality of `newtests/`, it's easier for us to test and update `tests/`

**Comment by gitonthescene** [comment]
I can add new tests if you like.  Is that what you're asking?  I only touched one file and didn't touch the tests.

    On Tuesday, November 19, 2019, 3:56:57 PM GMT+9, George Zahariev <notifications@github.com> wrote:  
 
 
Thanks for the PR!

Can you change the tests to be in tests/ (and in that format) instead of newtests/?

Unless they need some special functionality of newtests/, it's easier for us to test and update tests/

**Comment by gitonthescene** [comment]
Sorry.  I confused this with a different thread.  I see now that I'm only Cc-ed for having raised the issue.  Sorry for the confusion.
   On Tuesday, November 19, 2019, 6:18:19 PM GMT+9, Douglas Mennella <dougmabroad@yahoo.com> wrote:  
 
  I can add new tests if you like.  Is that what you're asking?  I only touched one file and didn't touch the tests.

    On Tuesday, November 19, 2019, 3:56:57 PM GMT+9, George Zahariev <notifications@github.com> wrote:  
 
 
Thanks for the PR!

Can you change the tests to be in tests/ (and in that format) instead of newtests/?

Unless they need some special functionality of newtests/, it's easier for us to test and update tests/

**Comment by thecotne** [comment]
@gkz done!

**Pull request closed without merging**
